[
  {
    type: "psatRW", subtype: "comprehension",
    passage: "When the framers of the Constitution gathered in Philadelphia in 1787, many delegates feared that a strong central government would simply repeat the abuses they had recently fought a war to escape. Others, however, worried that the loose confederation of states then in place could not pay its debts, defend its borders, or settle disputes between rival states. The compromise they eventually reached divided power between federal and state governments, hoping that each level would check the worst impulses of the other.",
    question: "The passage suggests that the framers' final design was shaped primarily by:",
    choices: [
      "competing fears about both weak and strong governments",
      "a shared admiration for the British parliamentary system",
      "a desire to eliminate state governments entirely",
      "pressure from foreign powers to centralize authority",
    ],
    correct: 0,
    explanation: "The passage describes two opposing fears — tyranny from a strong center and chaos from a weak one — and presents the compromise as a response to both. Choice A captures this tension directly.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The honeybee waggle dance, first decoded by Karl von Frisch in the 1940s, is one of the few examples of symbolic communication outside of humans. A foraging bee that has discovered a rich patch of flowers returns to the hive and performs a figure-eight pattern on the vertical comb. The angle of the central run, relative to straight up, indicates the direction of the food relative to the sun; the duration of the waggle encodes the distance. Hive mates that observe the dance can fly directly to the source, sometimes hundreds of meters away.",
    question: "According to the passage, the waggle dance is remarkable because it:",
    choices: [
      "involves the cooperation of an entire hive at once",
      "was the first behavior ever studied in honeybees",
      "uses symbols to convey specific information",
      "requires bees to memorize landmarks over long distances",
    ],
    correct: 2,
    explanation: "The opening sentence identifies the dance as a rare example of 'symbolic communication outside of humans.' Choice C reflects this. The other options are not supported.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "In the years following the Civil War, the United States transformed from a largely agricultural nation into an industrial powerhouse. Railroads stitched together distant markets, steel mills roared day and night, and immigrants flooded into rapidly growing cities. Yet the same decades that produced unprecedented wealth also produced grinding poverty in tenement neighborhoods, dangerous factory conditions, and bitter labor strikes. Critics began to call the era a 'Gilded Age' — referring to a thin layer of gold disguising a duller metal underneath.",
    question: "The term 'Gilded Age,' as used in the passage, was meant to suggest that the period's prosperity was:",
    choices: [
      "evenly shared across all social classes",
      "more appearance than substance for many Americans",
      "a direct result of government planning",
      "limited mainly to the southern states",
    ],
    correct: 1,
    explanation: "The passage explicitly explains the metaphor: a 'thin layer of gold disguising a duller metal underneath.' Choice B captures the idea that the prosperity hid deeper problems.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Black holes are regions of space where gravity is so intense that nothing, not even light, can escape once it crosses the boundary known as the event horizon. For decades, astronomers could only infer their existence indirectly, by watching how nearby stars and gas behaved. In 2019, however, the Event Horizon Telescope — a network of radio dishes spread across the globe — produced the first direct image of a black hole's shadow, confirming predictions that Einstein had made more than a century earlier.",
    question: "The author mentions the 2019 image primarily to:",
    choices: [
      "argue that Einstein's theories are now obsolete",
      "explain how radio telescopes are built",
      "describe a recent confirmation of long-standing predictions",
      "compare black holes to ordinary stars",
    ],
    correct: 2,
    explanation: "The passage frames the 2019 image as 'confirming predictions that Einstein had made more than a century earlier.' Choice C matches this purpose.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Maya pulled the letter from the stack of mail and turned it over twice, as if a second look might change what was printed on the envelope. She had been waiting for this answer for six weeks — long enough that she had almost convinced herself she no longer cared. But the moment her thumb slid under the flap, her hands began to shake, and she realized the waiting had been a kind of lie she had told herself.",
    question: "The passage most strongly suggests that Maya has been:",
    choices: [
      "pretending to feel less invested than she actually is",
      "hoping that the letter would never arrive",
      "preparing a careful response for whoever wrote her",
      "trying to ignore mail she finds unimportant",
    ],
    correct: 0,
    explanation: "The narrator says Maya 'had almost convinced herself she no longer cared,' but her shaking hands reveal that this self-assurance was 'a kind of lie.' Choice A captures the contrast.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "When supply of a good rises while demand stays constant, basic economic theory predicts that its price will fall. The reverse is also true: scarcity tends to drive prices up. This relationship explains why bottled water sells cheaply at a supermarket and yet commands several dollars in an airport terminal — not because the water itself is different, but because the alternatives available to buyers are very different in the two settings.",
    question: "The author uses the example of bottled water to illustrate that:",
    choices: [
      "manufacturers can charge whatever they wish for a product",
      "airports are designed to overcharge customers",
      "supermarkets purchase water at lower wholesale rates",
      "price depends partly on the choices buyers have available",
    ],
    correct: 3,
    explanation: "The passage attributes the price difference to the 'alternatives available to buyers' in each setting. Choice D reflects this point.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The Renaissance master Leonardo da Vinci is remembered today primarily as a painter, but in his own time he considered himself an engineer and inventor first. His notebooks, written in a peculiar mirror script, are filled with sketches of flying machines, water pumps, military fortifications, and human anatomy. Many of these designs were never built, and some could not have worked with the materials available in the fifteenth century. Yet they reveal a mind that refused to draw a sharp line between art and science.",
    question: "The passage primarily suggests that Leonardo:",
    choices: [
      "treated artistic and scientific work as deeply connected pursuits",
      "was unsuccessful as a painter and turned to invention instead",
      "kept his notebooks secret to prevent others from copying him",
      "designed only machines that could be built in his lifetime",
    ],
    correct: 0,
    explanation: "The final sentence states that Leonardo 'refused to draw a sharp line between art and science.' Choice A matches this characterization.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Coral reefs occupy less than one percent of the ocean floor, yet they shelter roughly a quarter of all marine species. The reefs themselves are built by tiny animals called polyps, which secrete calcium carbonate skeletons that accumulate over centuries into vast underwater structures. Warming seas now threaten these ecosystems: when water grows too hot, polyps expel the colorful algae that live inside them, leaving the reef bleached white and, eventually, dead.",
    question: "Which of the following best summarizes the central claim of the passage?",
    choices: [
      "Coral polyps are the smallest animals in the ocean.",
      "Calcium carbonate is the most common mineral in seawater.",
      "Reefs are biologically rich but vulnerable to rising temperatures.",
      "Ocean temperatures have remained stable in recent decades.",
    ],
    correct: 2,
    explanation: "The passage first establishes how much marine life depends on reefs, then describes the temperature threat. Choice C captures both halves of the argument.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Jane Austen's novels, written in the early nineteenth century, are sometimes dismissed as simple love stories. A closer reading reveals something sharper: her heroines navigate a world in which marriage is one of the few legal avenues to financial security available to women. The wit and irony for which Austen is celebrated often turn on this uncomfortable truth, exposing the social pressures that shaped what looked, on the surface, like romantic choices.",
    question: "The passage implies that critics who call Austen's novels 'simple love stories' tend to:",
    choices: [
      "underestimate the social commentary embedded in her plots",
      "exaggerate the importance of her female characters",
      "ignore her early works in favor of later ones",
      "praise her for the wrong reasons entirely",
    ],
    correct: 0,
    explanation: "The author contrasts the dismissive label with the 'sharper' reality that Austen exposes social and economic pressure on women. Choice A captures what such critics overlook.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The water cycle moves an enormous amount of moisture through Earth's atmosphere, oceans, and land each year. Sunlight evaporates water from the ocean's surface; the vapor rises, cools, and condenses into clouds; eventually, rain or snow returns the water to the surface, where rivers carry it back to the sea. Although the total volume of water on Earth has stayed nearly constant for billions of years, any individual molecule may travel through this cycle thousands of times.",
    question: "Which of the following best describes the main purpose of the passage?",
    choices: [
      "to argue that the water cycle is poorly understood by scientists",
      "to warn readers about the dangers of drought",
      "to compare ocean evaporation to river evaporation",
      "to describe how water moves continuously through different reservoirs",
    ],
    correct: 3,
    explanation: "The passage traces water from ocean to atmosphere to surface and back. Choice D captures this descriptive purpose.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "In 1955, Rosa Parks refused to give up her seat to a white passenger on a Montgomery, Alabama, bus. Her arrest was not a spontaneous accident; Parks had served for years as secretary of the local NAACP chapter and had attended training in nonviolent resistance. The boycott that followed her arrest lasted more than a year and helped propel a young minister named Martin Luther King Jr. into national prominence.",
    question: "The passage emphasizes that Parks's act of resistance was:",
    choices: [
      "the result of a sudden, impulsive decision",
      "rooted in years of activism and preparation",
      "opposed by the local NAACP at the time",
      "unrelated to the broader civil rights movement",
    ],
    correct: 1,
    explanation: "The passage explicitly states that Parks's arrest 'was not a spontaneous accident' and notes her prior NAACP work and training. Choice B reflects this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Volcanoes form most often along the boundaries where tectonic plates meet. When one plate slides beneath another, the descending rock melts under tremendous heat and pressure, producing magma that rises through cracks in the crust. Hawaii, however, sits in the middle of the Pacific Plate, far from any boundary. Its volcanoes are fed by a stationary plume of hot material — called a hotspot — that has burned through the moving plate for millions of years.",
    question: "The author mentions Hawaii primarily to:",
    choices: [
      "show that some volcanoes form outside the typical pattern",
      "argue that hotspot volcanoes are more dangerous than others",
      "explain why the Pacific Plate moves so quickly",
      "describe the largest volcano in the world",
    ],
    correct: 0,
    explanation: "Hawaii is introduced with 'however' as an exception to the boundary rule. Choice A captures this function.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The smartphone revolution that began in the late 2000s has reshaped daily life in ways that earlier technologies — telephones, televisions, even personal computers — did not. A single device now provides instant access to nearly every form of media, every social network, and every information service ever created. Critics argue that this constant availability has eroded attention spans and replaced face-to-face interaction; defenders counter that the same devices have given billions of people their first reliable access to banking, education, and emergency services.",
    question: "The passage suggests that smartphones are best understood as:",
    choices: [
      "a technology whose effects are mostly negative",
      "a technology whose effects are mostly positive",
      "a technology whose effects are mixed and still debated",
      "a technology unlikely to last beyond the next decade",
    ],
    correct: 2,
    explanation: "The passage presents both criticism and defense without endorsing either. Choice C captures this balanced framing.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "When the Japanese poet Matsuo Basho composed haiku in the seventeenth century, he sought to capture a single fleeting moment with as few words as possible. The form's rules — seventeen syllables, divided into lines of five, seven, and five — were meant not as a constraint but as a discipline. Basho believed that compression forced the writer to choose precisely the right images, leaving the reader to supply the emotional weight that the unwritten words implied.",
    question: "According to the passage, Basho viewed the rules of haiku as:",
    choices: [
      "a barrier that prevented true creative expression",
      "an outdated tradition in need of modernization",
      "a discipline that sharpened a writer's choices",
      "a system primarily designed for memorization",
    ],
    correct: 2,
    explanation: "The passage states that Basho saw the rules 'not as a constraint but as a discipline' that 'forced the writer to choose precisely the right images.' Choice C reflects this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "In 1789, a crowd of Parisians stormed the Bastille, a royal prison that had come to symbolize the abuses of absolute monarchy. The building itself held only seven prisoners that day, none of them political. Yet the act of seizing it ignited a revolution that would topple the French king, abolish feudal privilege, and inspire movements for liberty across Europe and the Americas. Symbols, the event reminded later generations, can carry weight far heavier than the things themselves.",
    question: "The passage suggests that the storming of the Bastille mattered chiefly because:",
    choices: [
      "it freed a large number of political prisoners",
      "the prison was the most heavily defended in France",
      "the king personally surrendered to the crowd that day",
      "its symbolic meaning outweighed its practical effect",
    ],
    correct: 3,
    explanation: "The passage notes that the prison held only seven non-political prisoners but that the event 'ignited a revolution.' The closing sentence emphasizes that 'symbols… can carry weight far heavier than the things themselves.' Choice D captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The placebo effect occurs when a patient experiences a real improvement in symptoms after receiving a treatment with no active ingredients — a sugar pill, for example. For decades, researchers treated placebos as scientific noise to be subtracted from drug trials. More recent studies, however, suggest that the brain's response to the act of being treated may itself produce measurable changes in pain perception, immune function, and mood. The phenomenon does not mean illnesses are imaginary; rather, it shows how closely belief and biology are intertwined.",
    question: "The author's main purpose in the passage is to:",
    choices: [
      "argue that drug trials should no longer use placebos",
      "show how scientific views of the placebo effect have shifted",
      "warn patients against trusting sugar pill treatments",
      "compare placebos to ordinary nutritional supplements",
    ],
    correct: 1,
    explanation: "The passage contrasts the older view (placebos as 'noise') with newer findings (real biological effects). Choice B captures this shift.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The Industrial Revolution transformed Britain in the late 1700s, but its effects on workers were rarely the ones reformers had hoped for. Factory hours often stretched to fourteen or more per day; children as young as six tended machines that frequently maimed them; and the smoky cities that sprang up around the new mills filled with disease. It was largely in response to these conditions that the first labor unions, factory inspection laws, and child welfare reforms slowly took shape over the following century.",
    question: "The passage primarily portrays the Industrial Revolution as:",
    choices: [
      "an unambiguous triumph of human progress",
      "an event that had little effect on ordinary workers",
      "a movement that was opposed by most factory owners",
      "a period whose costs prompted later reform efforts",
    ],
    correct: 3,
    explanation: "The passage describes harsh conditions and notes that reforms 'slowly took shape' in response. Choice D captures this cause-and-effect framing.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Birds descend from a group of small, feathered dinosaurs that survived the mass extinction event sixty-six million years ago. Modern paleontologists have uncovered fossils showing that many dinosaur species had feathers long before any could fly — feathers used, it seems, for insulation, display, or balance. Flight evolved later, perhaps from creatures that glided between branches, perhaps from ground runners whose flapping forelimbs gave them extra speed. Either way, today's sparrows and eagles are, in a strict scientific sense, living dinosaurs.",
    question: "The passage implies that feathers originally evolved for purposes that were:",
    choices: [
      "directly related to powered flight",
      "unrelated to flight and tied to other functions",
      "limited to a few specialized dinosaur species",
      "identical to their uses in modern birds",
    ],
    correct: 1,
    explanation: "The passage states that 'many dinosaur species had feathers long before any could fly,' listing insulation, display, and balance as early uses. Choice B captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The right to a jury trial, guaranteed in the Sixth Amendment, was no abstraction to the framers of the Bill of Rights. Many had personally faced colonial courts in which judges appointed by the British Crown decided cases without local input. By demanding that criminal charges be heard by 'an impartial jury of the State and district wherein the crime shall have been committed,' the framers sought to keep the power to convict close to the people most affected by the law.",
    question: "The passage suggests that the framers valued jury trials primarily because they:",
    choices: [
      "produced more efficient verdicts than judge trials",
      "had been used in ancient Greek and Roman courts",
      "kept the power to convict in the hands of local citizens",
      "required fewer government officials to operate",
    ],
    correct: 2,
    explanation: "The closing sentence makes the point directly: keeping 'the power to convict close to the people most affected by the law.' Choice C matches.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Antibiotic resistance occurs when bacteria evolve the ability to survive drugs designed to kill them. Every time an antibiotic is used, the bacteria most vulnerable to it die; any that happen to carry a useful mutation, however, may live and reproduce. Over many generations, populations of bacteria can shift entirely toward resistance. Public health experts warn that overuse of antibiotics — in livestock as well as in medicine — is speeding this process, and that infections once easily treated may soon become difficult to cure.",
    question: "Which of the following best describes the central idea of the passage?",
    choices: [
      "Overuse of antibiotics accelerates the evolution of resistance.",
      "Antibiotics are no longer effective against any bacteria.",
      "Bacteria reproduce more slowly than other microorganisms.",
      "Livestock are immune to most modern antibiotics.",
    ],
    correct: 0,
    explanation: "The passage explains how resistance evolves and identifies overuse as the accelerator. Choice A captures both pieces.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "In ancient Greek tragedy, the chorus served a role unfamiliar to modern theatergoers. A group of performers — often twelve to fifteen in number — chanted in unison, danced in patterns, and commented on the action of the play. They were not characters in the modern sense; they spoke for the community watching, voicing fears, moral judgments, and warnings that the protagonist could not. The chorus reminded audiences that the events on stage belonged not only to the hero but to the city as a whole.",
    question: "The passage primarily portrays the Greek chorus as:",
    choices: [
      "a group of secondary characters with private motives",
      "a voice that represented the audience and community",
      "a chorus of professional singers hired for entertainment",
      "a device used only in comedies, not tragedies",
    ],
    correct: 1,
    explanation: "The passage states that the chorus 'spoke for the community watching' and reminded the audience that events 'belonged… to the city as a whole.' Choice B captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The Federal Reserve, established in 1913, is the central bank of the United States. Among its many duties, perhaps the most consequential is setting short-term interest rates. By raising rates, the Fed makes borrowing more expensive and tends to slow economic activity; by lowering rates, it encourages borrowing and growth. Critics of either move are easy to find: tightening too quickly can throw people out of work, while loosening too freely can fuel inflation. Few jobs in government require steadier nerves.",
    question: "The passage suggests that managing interest rates is difficult mainly because:",
    choices: [
      "the Federal Reserve lacks legal authority over banks",
      "inflation and unemployment cannot be measured accurately",
      "any decision carries significant trade-offs and critics",
      "interest rates have little effect on the broader economy",
    ],
    correct: 2,
    explanation: "The passage emphasizes the trade-off — tightening risks unemployment, loosening risks inflation — and the inevitable critics. Choice C captures this difficulty.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "When Theo first picked up the violin, his teacher warned him that the early weeks would sound 'terrible to everyone, including yourself.' She was right. For months, his bowing produced screeches that drove his younger sister out of the room. But each evening Theo practiced anyway, and one Saturday morning, almost without noticing, he realized that the long, smooth note he had just drawn was, in fact, music. The change had happened so gradually that no single day could be marked as the turning point.",
    question: "The passage suggests that Theo's progress on the violin was:",
    choices: [
      "the result of a single breakthrough lesson",
      "discouraged by his family throughout the year",
      "faster than his teacher had expected",
      "achieved through gradual, unnoticed daily improvement",
    ],
    correct: 3,
    explanation: "The closing sentences describe Theo's improvement as so gradual that 'no single day could be marked as the turning point.' Choice D captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "A democracy depends on more than free elections. Citizens must be willing to accept results they do not like, to argue with neighbors without resorting to violence, and to trust that institutions — courts, agencies, the press — will check abuses of power. These habits are not written into any constitution; they are passed down through schools, families, and civic life. When such habits weaken, even a country with formal democratic rules can drift toward something harsher.",
    question: "The main claim of the passage is that democracy depends on:",
    choices: [
      "frequent and fair elections above all else",
      "informal habits and trust as much as legal rules",
      "strong leaders who can enforce constitutional limits",
      "a written constitution that lists every citizen right",
    ],
    correct: 1,
    explanation: "The passage explicitly contrasts formal rules with the 'habits' passed through schools and families, and warns that elections alone are not enough. Choice B captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Photosynthesis, the process by which plants convert sunlight into chemical energy, is sometimes described as the foundation of nearly all life on Earth. Plants use light to combine carbon dioxide from the air with water from the soil, producing sugars and releasing oxygen as a byproduct. Animals — including humans — depend on plants for both the energy stored in those sugars and the oxygen needed to breathe. Even most of the fossil fuels we burn today are the buried remains of long-dead plants.",
    question: "The author calls photosynthesis 'the foundation of nearly all life on Earth' chiefly because it:",
    choices: [
      "occurs in every region of the planet, including the deep sea",
      "uses materials that are otherwise toxic to most organisms",
      "produces both the food and the oxygen on which animals rely",
      "is the only chemical reaction performed by living things",
    ],
    correct: 2,
    explanation: "The passage explains that animals depend on plants for 'the energy stored in those sugars and the oxygen needed to breathe.' Choice C captures this dual dependence.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Few writers have shaped American literature as quietly as Willa Cather. Her novels — set most often on the Nebraska prairie of her youth — avoid the dramatic plots of her contemporaries in favor of patient attention to landscape, weather, and the inner lives of immigrant farmers. Critics in her own time sometimes mistook this restraint for simplicity. Today, readers more often recognize it as a deliberate art, one that finds depth in the ordinary rather than the spectacular.",
    question: "The passage suggests that Cather's restraint was:",
    choices: [
      "a sign that she lacked confidence as a writer",
      "an intentional stylistic choice often misread by early critics",
      "a result of her inexperience with prairie life",
      "imposed on her by editors who preferred shorter novels",
    ],
    correct: 1,
    explanation: "The passage contrasts critics who 'mistook this restraint for simplicity' with the modern view of it as 'a deliberate art.' Choice B captures this contrast.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Sleep, long treated by scientists as a kind of biological pause button, turns out to be one of the busiest times in the brain. During the night, neurons strengthen the connections that store the day's memories, flush out waste products that accumulate during waking hours, and rehearse skills learned earlier in the day. Animals deprived of sleep for extended periods show impaired learning, weakened immune systems, and eventually, in severe cases, organ failure. Far from being lost time, sleep does work the body cannot do while awake.",
    question: "The author's main point about sleep is that it:",
    choices: [
      "is more dangerous than scientists once believed",
      "differs greatly between humans and other animals",
      "performs essential functions that the body cannot perform while awake",
      "becomes less important as a person ages",
    ],
    correct: 2,
    explanation: "The closing sentence summarizes the argument directly: sleep 'does work the body cannot do while awake.' Choice C matches.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The Mongol Empire, founded by Genghis Khan in the early 1200s, eventually stretched from the Pacific coast of Asia to the gates of Vienna. For all the destruction the Mongols inflicted on conquered cities, the empire they built also opened the so-called Silk Road to a level of safe travel never seen before. Merchants, missionaries, and inventors moved across thousands of miles of Mongol territory, carrying paper money, gunpowder recipes, and printed books westward, and silver and woolen cloth eastward.",
    question: "The passage suggests that the Mongol Empire is best understood as:",
    choices: [
      "primarily a force of destruction with no lasting benefits",
      "a peaceful trading network from beginning to end",
      "an empire that opposed contact between East and West",
      "both destructive and an unintended driver of exchange",
    ],
    correct: 3,
    explanation: "The passage acknowledges 'destruction' but also describes the Mongols opening safe trade routes that carried goods and ideas across continents. Choice D reflects this dual portrayal.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Modern skyscrapers depend on two innovations that did not exist for most of human history: structural steel and the safety elevator. Stone and brick buildings could only rise so high before the lower walls had to be made impossibly thick to bear the weight above. Steel framing transferred that weight onto slim columns, freeing the outer walls to become little more than skins of glass. Elisha Otis's safety brake, demonstrated in 1854, made it practical for people to reach the upper floors that steel suddenly allowed.",
    question: "According to the passage, skyscrapers were made possible by:",
    choices: [
      "the invention of stronger forms of brick and stone",
      "the combination of steel framing and safety elevators",
      "advances in the production of large window glass",
      "the spread of electricity into urban buildings",
    ],
    correct: 1,
    explanation: "The passage identifies 'structural steel and the safety elevator' as the two key innovations and explains the role of each. Choice B matches.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Sociologists who study online communities have noticed a recurring pattern: small groups of highly active users produce the majority of content, while a much larger group reads, watches, and occasionally reacts. This imbalance, sometimes called the '1 percent rule,' is not necessarily a sign of failure. Quiet observers may still benefit from a community's information, recommend it to friends, or step forward to contribute when a topic strikes them personally.",
    question: "The author's attitude toward the '1 percent rule' can best be described as:",
    choices: [
      "alarmed, because it shows most users are unengaged",
      "enthusiastic, because it makes communities easier to manage",
      "skeptical, because the data behind it are unreliable",
      "neutral, presenting it as common and not inherently negative",
    ],
    correct: 3,
    explanation: "The passage notes the imbalance but explicitly says it 'is not necessarily a sign of failure,' offering reasons quiet users still matter. Choice D captures the balanced tone.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Few historical figures are as contested as Christopher Columbus. For centuries, schoolbooks in the Americas celebrated him as a daring explorer who 'discovered' a new world. More recent scholarship emphasizes that the lands he reached were already home to millions of people, and that the contact he initiated brought disease, enslavement, and the violent overthrow of existing societies. Neither portrait, taken alone, captures the full weight of the historical record.",
    question: "The passage primarily argues that any honest account of Columbus must:",
    choices: [
      "abandon all references to his role as an explorer",
      "include both his daring voyages and the harm that followed contact",
      "rely only on sources written by Indigenous historians",
      "treat him as the most important figure of his century",
    ],
    correct: 1,
    explanation: "The final sentence says that 'neither portrait, taken alone, captures the full weight of the historical record.' Choice B reflects this call for a fuller picture.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The Earth's magnetic field, generated deep in the planet's molten iron core, does more than steer compass needles. It deflects most of the high-energy particles streaming from the sun, protecting the atmosphere — and the life that depends on it — from being slowly stripped away. Mars, by contrast, lost its magnetic field billions of years ago, and with it most of its air and water. The thin, dry atmosphere we see there today may offer a glimpse of what Earth could become if its own field ever faltered.",
    question: "The author mentions Mars chiefly to:",
    choices: [
      "argue that humans should focus on exploring Mars",
      "compare the size of Mars and Earth",
      "illustrate the consequences of losing a magnetic field",
      "describe the chemical makeup of the Martian core",
    ],
    correct: 2,
    explanation: "Mars is introduced as a contrast: it lost its magnetic field and, with it, its atmosphere. Choice C captures the illustrative function.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Public libraries have transformed remarkably little, in spirit, over the past century. The collections may now include audiobooks, computers, and streaming services alongside printed books, and the buildings often double as community centers, but the core idea remains constant: knowledge held in common, available to anyone regardless of income. That principle, simple as it sounds, was once novel enough that nineteenth-century skeptics warned it would breed laziness and crime.",
    question: "Which of the following best describes the author's view of public libraries?",
    choices: [
      "Their original mission has been replaced by digital services.",
      "Their core principle has survived even as their offerings have expanded.",
      "They were a poorly conceived nineteenth-century experiment.",
      "Their main function is to serve as community gathering spaces.",
    ],
    correct: 1,
    explanation: "The passage emphasizes that, despite added services, 'the core idea remains constant.' Choice B captures this continuity.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Spiders are often grouped with insects in casual conversation, but the two are only distantly related. Insects have six legs, three body segments, and antennae; spiders have eight legs, two body segments, and no antennae at all. Spiders also produce silk from glands in their abdomens — a substance with a tensile strength, gram for gram, comparable to that of steel. Confusing the two animals is harmless enough, but it obscures just how unusual spiders really are.",
    question: "The passage primarily seeks to:",
    choices: [
      "warn readers about the dangers spiders pose to people",
      "describe how spiders use silk to catch their prey",
      "compare insect and spider populations across regions",
      "correct a common misconception about how spiders are classified",
    ],
    correct: 3,
    explanation: "The passage opens by noting that spiders 'are often grouped with insects' and then lists the differences. Choice D captures the corrective purpose.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Renewable energy sources — wind, solar, hydro, geothermal — produce electricity without burning fossil fuels and so without releasing the carbon dioxide that drives climate change. Each, however, has its own constraints. The wind does not always blow, the sun does not always shine, and even the most ambitious dam cannot be built in a region without rivers. Most plans for a fully renewable grid therefore depend not on any single source but on a careful mix of generation and large-scale energy storage.",
    question: "The passage suggests that the future of renewable energy will most likely involve:",
    choices: [
      "a single dominant source that replaces all others",
      "a combination of multiple sources together with storage",
      "a gradual return to nuclear power as a substitute",
      "a sharp reduction in the world's overall electricity use",
    ],
    correct: 1,
    explanation: "The closing sentence states that plans 'depend not on any single source but on a careful mix of generation and large-scale energy storage.' Choice B reflects this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The Suez Canal, completed in 1869, cut a direct waterway between the Mediterranean and the Red Sea. Before its opening, ships traveling between Europe and Asia had to round the entire continent of Africa — a journey of weeks that the canal reduced to days. The economic consequences were immense: goods that had once been luxuries became affordable, and the strategic importance of nearby ports rose sharply. Control of the canal became a recurring source of conflict for more than a century afterward.",
    question: "Which choice best summarizes the passage?",
    choices: [
      "The Suez Canal greatly shortened shipping routes and reshaped trade and politics.",
      "The Suez Canal was an engineering project that took decades to design.",
      "The Suez Canal made the Mediterranean Sea unsafe for naval vessels.",
      "The Suez Canal is no longer as important as it was in the nineteenth century.",
    ],
    correct: 0,
    explanation: "The passage describes the canal's effect on travel time, trade, and political conflict. Choice A captures all three threads.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The painter Vincent van Gogh sold only a handful of works during his lifetime and lived for years on money sent by his younger brother, Theo. The brothers' correspondence, preserved across hundreds of letters, reveals an artist who was painfully aware of how unfashionable his thick brushstrokes and intense colors appeared to the buyers of his day. Today, those same qualities are precisely why his paintings are treasured — and why a single canvas can sell for more than the entire art trade of his time would have predicted.",
    question: "The passage implies that van Gogh's work is now valued for:",
    choices: [
      "qualities that audiences in his lifetime largely disliked",
      "subjects that closely resembled what was fashionable in his era",
      "techniques that other painters of his time also used widely",
      "its careful imitation of earlier Dutch masters",
    ],
    correct: 0,
    explanation: "The passage contrasts the rejection of van Gogh's 'thick brushstrokes and intense colors' in his day with their being 'precisely why his paintings are treasured' today. Choice A captures this reversal.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "A common myth about the human brain holds that people use only 10 percent of it. Modern imaging techniques have shown this to be false. Different tasks light up different regions, but over the course of a single day virtually every part of the brain becomes active at some point. The 10 percent claim, whose origins are murky, persists in popular culture probably because it offers a hopeful suggestion — that hidden powers lie within easy reach, if only we could turn on the rest.",
    question: "The passage attributes the persistence of the '10 percent myth' chiefly to:",
    choices: [
      "scientific evidence that has not yet been published",
      "deliberate efforts by educators to motivate students",
      "the appeal of the idea that we have untapped abilities",
      "confusion between the brain and the nervous system",
    ],
    correct: 2,
    explanation: "The final sentence speculates that the myth survives because it 'offers a hopeful suggestion' of untapped potential. Choice C reflects this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The novelist James Baldwin grew up in Harlem in the 1920s and 1930s, the eldest of nine children in a household marked by poverty and a difficult stepfather. He found his way to literature through the public library and the church, both of which gave him a sense of language as something powerful enough to confront the injustices he witnessed daily. Years later, his essays would urge American readers to look at race, sexuality, and identity with the same unflinching honesty he had taught himself in childhood.",
    question: "The passage suggests that Baldwin's later writing was rooted in:",
    choices: [
      "a desire to escape the realities he had grown up with",
      "his formal training at university programs in writing",
      "his isolation from the African American literary community",
      "an early belief in language as a means of facing difficult truths",
    ],
    correct: 3,
    explanation: "The passage describes Baldwin learning to see language as 'powerful enough to confront the injustices he witnessed.' Choice D captures the source of his later honesty.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Antarctica is the only continent without a permanent human population. International agreements, beginning with the 1959 Antarctic Treaty, set the region aside for peaceful scientific research and prohibit military activity, mining, and territorial claims. The arrangement is fragile in some respects — it relies on the continued goodwill of dozens of governments — but it has held for more than six decades and remains one of the more successful examples of international cooperation in modern history.",
    question: "The author's attitude toward the Antarctic Treaty system can best be described as:",
    choices: [
      "highly critical, viewing it as nearly certain to collapse",
      "cautiously positive, viewing it as imperfect but largely successful",
      "uncertain, finding the available evidence insufficient",
      "indifferent, treating it as a minor diplomatic matter",
    ],
    correct: 1,
    explanation: "The passage calls the arrangement 'fragile in some respects' but praises it as 'one of the more successful examples of international cooperation.' Choice B captures this balanced positive view.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Earthquake-prone cities have developed surprisingly different strategies for protecting their buildings. Tokyo emphasizes flexibility, designing skyscrapers that sway visibly during a tremor but absorb the motion without breaking. Los Angeles relies more on rigid bracing, intended to keep structures upright through the shaking. Older cities such as Istanbul face a harder problem: many of their most important buildings predate any modern earthquake code, and retrofitting them can be expensive enough that the work proceeds only slowly.",
    question: "The passage primarily contrasts approaches to earthquake safety in order to:",
    choices: [
      "argue that one city's strategy is clearly superior",
      "warn that ancient buildings are doomed in major quakes",
      "show that solutions vary with local conditions and constraints",
      "explain why earthquakes occur more often in some regions",
    ],
    correct: 2,
    explanation: "The passage describes three different strategies tied to different cities' situations, without ranking them. Choice C captures the comparative purpose.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Long before written history, peoples across the Pacific accomplished one of humanity's most remarkable feats: the settlement of nearly every habitable island scattered across thousands of miles of open ocean. Using double-hulled canoes, knowledge of stars, wave patterns, and bird flight, Polynesian navigators reached islands as distant as Hawaii, Easter Island, and New Zealand. European explorers, arriving centuries later with compasses and charts, were often astonished to find these settlements already long established.",
    question: "The passage emphasizes that Polynesian navigation was:",
    choices: [
      "accidental, depending mostly on storms blowing canoes off course",
      "limited to short voyages between nearby islands",
      "shared openly with European explorers when they arrived",
      "highly skilled, relying on a deep knowledge of natural signs",
    ],
    correct: 3,
    explanation: "The passage describes navigators using stars, waves, and bird flight to reach distant islands and notes Europeans' astonishment. Choice D captures this skill.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Octopuses, despite having no backbone, display levels of problem-solving that rival those of many vertebrates. In laboratory experiments, they have opened jars to retrieve food, escaped through narrow gaps when no human was watching, and even appeared to recognize specific researchers who handled them. What makes these behaviors more striking is that octopuses live solitary lives and pass on no learned behavior from one generation to the next. Each individual must, in effect, figure the world out from scratch.",
    question: "The passage suggests that octopus intelligence is especially surprising because it:",
    choices: [
      "develops in isolation, without being passed between generations",
      "depends on the presence of a complex skeleton",
      "is identical to that of trained laboratory rats",
      "improves only when octopuses live in large social groups",
    ],
    correct: 0,
    explanation: "The passage emphasizes that octopuses are solitary and 'pass on no learned behavior,' so each one 'must… figure the world out from scratch.' Choice A captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The right to free speech, set out in the First Amendment, has never been absolute. Courts have long recognized exceptions for fraud, threats, and incitement to immediate violence. What has changed over time is the willingness to extend the amendment's protections to speech that the majority finds offensive or unpopular. Cases involving wartime protests, controversial books, and political symbols have steadily widened the range of expression the government may not punish — a trend that, however uneven, has been hard to reverse.",
    question: "The author characterizes the history of First Amendment protections as:",
    choices: [
      "shrinking steadily as new exceptions are recognized",
      "remaining the same since the amendment was ratified",
      "expanding overall, though not without limits or setbacks",
      "primarily focused on commercial advertising",
    ],
    correct: 2,
    explanation: "The passage describes a trend of 'steadily widened' protection that is 'uneven' but 'hard to reverse.' Choice C captures this growth-with-limits view.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Tomas had memorized every street on the bus route, every storefront, every traffic light that took too long to turn green. After three years of riding the same line to and from work, he could close his eyes between stops and know, almost to the second, where the bus had reached. He found a strange comfort in this — as though the city, for all its size and noise, had become a kind of large, slow clock that he alone knew how to read.",
    question: "The passage most directly characterizes Tomas as someone who:",
    choices: [
      "feels overwhelmed by the size and pace of his city",
      "longs to move to a different neighborhood entirely",
      "spends most of his time avoiding contact with strangers",
      "finds reassurance in the predictability of his daily route",
    ],
    correct: 3,
    explanation: "The passage says Tomas 'found a strange comfort' in the route's predictability and describes the city as 'a kind of large, slow clock that he alone knew how to read.' Choice D captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Although usually presented as a single event, the Scientific Revolution unfolded over more than two centuries. It included Copernicus's argument, in 1543, that the Earth orbits the sun; Galileo's telescopic observations a century later; and Newton's laws of motion, published in 1687. What linked these figures was less a shared subject than a shared method: a willingness to test received ideas against careful observation and mathematics. The slow accumulation of such challenges changed what counted as knowledge itself.",
    question: "The passage suggests that the Scientific Revolution is best understood as:",
    choices: [
      "a single discovery made by Copernicus in 1543",
      "a long, gradual shift united by a common method of inquiry",
      "a rebellion led mainly against religious institutions",
      "an event that produced no lasting effect on later science",
    ],
    correct: 1,
    explanation: "The passage stresses that the revolution 'unfolded over more than two centuries' and was linked by 'a shared method.' Choice B captures both points.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Most plastics we use today were invented in the twentieth century and were celebrated, at first, for their convenience and low cost. What few of their inventors anticipated was how long these materials would persist in the environment. A polyethylene bag, used for perhaps twenty minutes, can outlast the person who carried it by hundreds of years. Modern efforts to design plastics that break down more quickly — or to replace them with biodegradable substitutes — are partly an attempt to undo a problem an earlier generation did not see coming.",
    question: "The passage primarily argues that the problem of plastic pollution is:",
    choices: [
      "a recent issue caused entirely by consumer carelessness",
      "a deliberate trade-off accepted by twentieth-century chemists",
      "an unintended consequence that took decades to recognize",
      "exaggerated by environmental groups in recent years",
    ],
    correct: 2,
    explanation: "The passage notes that 'few of their inventors anticipated' how long plastics would last, framing the issue as a problem 'an earlier generation did not see coming.' Choice C reflects this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Maps are never neutral. Every projection — the mathematical method used to flatten a round globe onto a flat page — must distort either the shape or the size of land masses, and often both. The familiar Mercator map, designed in the 1500s for sea navigation, exaggerates the size of regions near the poles, making Greenland appear nearly the size of Africa when it is, in fact, about fourteen times smaller. The choice of projection reflects what a mapmaker considers worth preserving.",
    question: "The passage uses Greenland's apparent size to illustrate that:",
    choices: [
      "older maps tend to be more accurate than modern ones",
      "Greenland has shrunk significantly since the 1500s",
      "Africa was historically considered less important than Europe",
      "the choice of projection influences how viewers perceive the world",
    ],
    correct: 3,
    explanation: "The Greenland example shows how a particular projection distorts size; the passage connects this to the mapmaker's choices. Choice D captures the lesson.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Few inventions transformed daily life as quietly as the bicycle. Introduced in roughly its modern form in the late nineteenth century, it offered ordinary people — for the first time — independent travel over distances of ten or twenty miles at little cost. Historians have noted that bicycles especially expanded the freedom of women, who could now travel to work, school, or social gatherings without depending on a horse, a carriage, or a chaperone. Critics at the time worried, accurately, that the new mobility would unsettle older social arrangements.",
    question: "According to the passage, contemporary critics of the bicycle were 'accurate' in expecting that it would:",
    choices: [
      "make horses and carriages permanently obsolete",
      "disrupt established patterns of social life, especially for women",
      "encourage women to abandon paid work entirely",
      "fail to spread beyond a small group of wealthy enthusiasts",
    ],
    correct: 1,
    explanation: "The passage credits the bicycle with expanding women's freedom and notes that critics 'accurately' feared it would 'unsettle older social arrangements.' Choice B captures this.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The novel '1984,' published by George Orwell in 1949, imagines a future in which a totalitarian state monitors every word and gesture of its citizens. Orwell, who had observed authoritarian regimes in both Europe and Asia, intended the book less as a prediction than as a warning. His concern was not that the specific technologies of his novel — telescreens, thought police, doctored newspapers — would arrive on schedule, but that the habits of mind they required might creep into any society inattentive to its own freedoms.",
    question: "The passage suggests that Orwell's primary purpose in writing '1984' was to:",
    choices: [
      "predict the exact technologies of the late twentieth century",
      "criticize a specific government he had once worked for",
      "warn readers about attitudes that could erode freedom anywhere",
      "argue that surveillance technology is never harmful",
    ],
    correct: 2,
    explanation: "The passage explicitly states that Orwell wrote the book as 'a warning' about 'habits of mind' that could 'creep into any society inattentive to its own freedoms.' Choice C matches.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The brain's hippocampus, a small, seahorse-shaped structure tucked deep inside each temporal lobe, plays a central role in forming new memories. Patients who suffer damage to both hippocampi often retain the ability to recall events from before the injury but cannot reliably store new ones afterward. They may, for example, hold a conversation perfectly well, then forget that it ever happened within minutes. Such cases helped researchers separate memory into distinct systems, only some of which depend on this single, fragile structure.",
    question: "The passage primarily uses cases of hippocampal damage to:",
    choices: [
      "argue that all memory depends on a single brain region",
      "show that the hippocampus is involved in forming new memories but not retrieving older ones",
      "demonstrate that memory loss is usually temporary",
      "explain why older adults remember childhood events vividly",
    ],
    correct: 1,
    explanation: "The passage notes that patients 'retain the ability to recall events from before the injury but cannot reliably store new ones afterward.' Choice B captures this distinction.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Few political ideas have proved as portable as the notion of natural rights. In John Locke's writings of the late 1600s, every person was said to possess basic rights to life, liberty, and property simply by virtue of being human. Less than a century later, the same language appeared, slightly altered, in the American Declaration of Independence. Within another fifty years, the French Revolution and several Latin American independence movements had borrowed it again, each adapting the phrase to local circumstances.",
    question: "The passage emphasizes that the idea of natural rights:",
    choices: [
      "originated in the American Declaration of Independence",
      "spread across very different political movements over time",
      "was rejected by most thinkers outside of England",
      "lost its influence by the early nineteenth century",
    ],
    correct: 1,
    explanation: "The passage traces the idea from Locke to the American, French, and Latin American movements, calling it 'portable.' Choice B captures this spread.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "Glaciers are sometimes called the world's largest reservoirs of freshwater, but they are also among the slowest. A single grain of ice near the top of a glacier may take centuries to grind its way down to the foot of the valley, where it finally melts into a river. As global temperatures rise, however, many glaciers are losing mass faster than the slow accumulation of new snow can replace it. Downstream cities that depend on glacial meltwater for drinking and irrigation face an uncertain future.",
    question: "The passage suggests that the chief concern raised by glacier loss is:",
    choices: [
      "the threat to communities that rely on glacial meltwater",
      "the danger that glaciers will collide with coastal cities",
      "the loss of habitat for animals that live on the ice",
      "the disappearance of opportunities for scientific research",
    ],
    correct: 0,
    explanation: "The final sentence highlights 'downstream cities that depend on glacial meltwater… face an uncertain future.' Choice A captures this concern.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "When the British surrendered at Yorktown in 1781, the American Revolution effectively ended — but the harder work of building a country had only begun. The new nation faced enormous war debts, a weak central government, disputes over slavery, and uncertain relationships with foreign powers. The Constitution, drafted six years later, was an attempt to address some of these problems, though it left others — most notably slavery — for future generations to resolve, often through means far more painful than negotiation.",
    question: "The passage primarily portrays the years immediately after Yorktown as:",
    choices: [
      "a period of celebration and easy political agreement",
      "a time when the new government quickly settled the question of slavery",
      "an era when American leaders looked mainly to Britain for guidance",
      "a difficult period in which many fundamental problems remained unresolved",
    ],
    correct: 3,
    explanation: "The passage lists war debts, weak government, slavery, and foreign relations as unresolved problems, and notes that some were left to later generations. Choice D captures this difficulty.",
  },
  {
    type: "psatRW", subtype: "comprehension",
    passage: "The architect Frank Lloyd Wright spent his long career arguing that a building should grow out of its site rather than be imposed upon it. His most famous house, Fallingwater, is built directly over a waterfall in rural Pennsylvania, its cantilevered terraces echoing the layers of rock beneath. Critics sometimes complained that his designs were impractical — roofs leaked, ceilings ran low — but few denied that he had taught American architecture to treat the landscape as a partner rather than an obstacle.",
    question: "The passage suggests that Wright's lasting contribution to architecture was:",
    choices: [
      "a focus on practical reliability over visual beauty",
      "a way of designing buildings that responds to their surroundings",
      "a preference for traditional European styles",
      "an emphasis on using only materials produced locally",
    ],
    correct: 1,
    explanation: "The passage describes Wright's central principle — a building should 'grow out of its site' and treat 'the landscape as a partner.' Choice B captures this lasting idea.",
  },
]
