[
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The new wing of the museum, which opened last spring, <u>contain</u> over three hundred artifacts from ancient Mesopotamia.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "contains",
      "are containing",
      "contain it",
    ],
    correct: 1,
    explanation: "The singular subject 'wing' requires the singular verb 'contains.' The original 'contain' is plural and disagrees with the subject. 'Are containing' is both plural and unnecessarily progressive. 'Contain it' adds a redundant pronoun and still has the agreement error.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Each of the students <u>were asked</u> to bring a permission slip signed by a parent or guardian.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "were being asked",
      "was asked",
      "are asked",
    ],
    correct: 2,
    explanation: "'Each' is a singular indefinite pronoun and takes a singular verb: 'was asked.' The phrase 'of the students' does not change the subject. 'Were asked' and 'were being asked' are plural; 'are asked' shifts tense incorrectly.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Walking through the forest at dusk, <u>the sound of an owl could be heard by Maria</u>.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "an owl was heard by Maria",
      "the owl's sound was heard",
      "Maria heard the sound of an owl",
    ],
    correct: 3,
    explanation: "The introductory phrase 'Walking through the forest at dusk' must modify the person doing the walking. Only choice D makes Maria the subject of the main clause, fixing the dangling modifier. The other options leave 'the sound' or 'an owl' as the subject, implying the sound or owl was walking.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The chef prepared three dishes for the competition: a roasted duck, a vegetable risotto, <u>and she also made</u> a chocolate souffle.",
    question: "Which choice best maintains parallelism in the list?",
    choices: [
      "NO CHANGE",
      "and a chocolate souffle",
      "also a chocolate souffle was made",
      "and making a chocolate souffle",
    ],
    correct: 1,
    explanation: "Parallel structure requires each item in the list to share the same form. The first two items are noun phrases ('a roasted duck,' 'a vegetable risotto'), so the third should match: 'a chocolate souffle.' The other choices break the noun-phrase pattern with verbs or new clauses.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "After the long hike, the campers were exhausted; <u>however they still managed</u> to set up their tents before sunset.",
    question: "Which choice provides the correct punctuation?",
    choices: [
      "NO CHANGE",
      "however; they still managed",
      "however, they still managed",
      "however they still, managed",
    ],
    correct: 2,
    explanation: "'However' as a conjunctive adverb at the beginning of a clause is followed by a comma. The semicolon before it correctly joins the two independent clauses, but a comma must follow 'however.' Choice B double-punctuates; choice D places a comma in the wrong spot.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The library's collection of rare books <u>are housed</u> in a climate-controlled room on the third floor.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "have been housed",
      "were housing",
      "is housed",
    ],
    correct: 3,
    explanation: "The subject is 'collection' (singular), not 'rare books.' Singular subjects take singular verbs: 'is housed.' 'Are housed' and 'have been housed' are plural. 'Were housing' switches to active voice incorrectly and is also past progressive.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Although the experiment failed on its first attempt, <u>its results</u> still gave the team valuable information about the reaction.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "it's results",
      "its' results",
      "their results",
    ],
    correct: 0,
    explanation: "'Its' is the possessive form (no apostrophe) and is correct here — the experiment owns the results. 'It's' is a contraction for 'it is,' which doesn't make sense. 'Its'' is not a valid English form. 'Their' is plural and would not match the singular 'experiment.'",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The teacher asked the students to read the chapter quietly, take detailed notes, <u>and that they answer</u> the questions at the end.",
    question: "Which choice best maintains parallelism?",
    choices: [
      "NO CHANGE",
      "and to answer",
      "and answer",
      "and they should answer",
    ],
    correct: 2,
    explanation: "The list begins with bare verbs after 'to': '(to) read,' '(to) take,' and so the third item should also be a bare verb: 'answer.' Adding 'to' or a new clause breaks the parallelism. 'Read,' 'take,' and 'answer' share the same infinitive base governed by the leading 'to.'",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "There were <u>less</u> students in the auditorium than the principal had expected.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "lesser",
      "least",
      "fewer",
    ],
    correct: 3,
    explanation: "'Fewer' is used with countable nouns (students); 'less' is used with uncountable nouns (water, time). 'Lesser' implies inferior quality, not quantity. 'Least' is a superlative and would not fit a two-way comparison.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The new policy will <u>effect</u> every employee in the company, regardless of department.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "affect",
      "effected",
      "affecting",
    ],
    correct: 1,
    explanation: "'Affect' is the verb meaning 'to influence'; 'effect' as a verb means 'to bring about,' which doesn't fit the sentence. The policy will influence employees, so 'affect' is right. 'Effected' is past tense and clashes with 'will.' 'Affecting' is not a finite verb.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "By the time the rescue team arrived, the climber <u>has been</u> stranded on the ledge for over six hours.",
    question: "Which choice best maintains verb-tense consistency?",
    choices: [
      "NO CHANGE",
      "was being",
      "had been",
      "is",
    ],
    correct: 2,
    explanation: "The main clause uses past tense ('arrived'), so the action that happened before it should use past perfect: 'had been.' 'Has been' is present perfect and doesn't sequence properly. 'Was being' is past progressive; 'is' shifts to present.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The professor handed out the syllabus, explained the grading policy, <u>and then she dismissed</u> the class early.",
    question: "Which choice is most concise while preserving meaning?",
    choices: [
      "NO CHANGE",
      "and then dismissing",
      "and she also dismissed",
      "and dismissed",
    ],
    correct: 3,
    explanation: "The list already establishes 'the professor' as the subject; repeating 'she' is redundant. 'And dismissed' continues the parallel verb structure cleanly. 'Dismissing' breaks parallelism, and 'she also' is wordy and unnecessary.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Neither the coach nor the players <u>was willing</u> to comment on the team's performance after the loss.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "is willing",
      "were willing",
      "has been willing",
    ],
    correct: 2,
    explanation: "With 'neither...nor,' the verb agrees with the subject closest to it. 'Players' is plural, so the verb must be plural: 'were willing.' 'Was willing' and 'is willing' are singular; 'has been willing' is also singular.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The artist's paintings were vivid and emotional; <u>nevertheless, they failed</u> to attract much attention from critics.",
    question: "Which choice provides the most logical transition?",
    choices: [
      "NO CHANGE",
      "therefore, they failed",
      "for example, they failed",
      "in addition, they failed",
    ],
    correct: 0,
    explanation: "The contrast between being vivid/emotional and failing to attract attention requires a contrast transition. 'Nevertheless' signals that contrast. 'Therefore' implies cause, 'for example' implies illustration, and 'in addition' implies adding similar info — none fit.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The two brothers, both <u>who is</u> avid hikers, decided to spend the weekend in the mountains.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "of which are",
      "of whom are",
      "of who are",
    ],
    correct: 2,
    explanation: "'Both of whom' is the correct construction when referring to two people in a nonrestrictive clause. 'Whom' is the object of 'of.' 'Who is' is singular and ungrammatical here; 'of which' is for things, not people; 'of who' uses the wrong case.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The recipe calls for two cups of flour, a teaspoon of salt <u>and three large eggs which are at room temperature</u>.",
    question: "Which choice provides the clearest and most properly punctuated version of the underlined text?",
    choices: [
      "NO CHANGE",
      ", and three large eggs, at room temperature",
      "and three large eggs, at room temperature",
      ", and three large eggs at room temperature",
    ],
    correct: 3,
    explanation: "A serial comma before 'and' is needed in a list of three items, and 'at room temperature' modifies 'eggs' tightly enough that no comma is needed. The original omits the comma before 'and'; choice B adds an unnecessary comma; choice C omits both.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The committee reached a decision <u>that they all agreed on it</u> after several hours of debate.",
    question: "Which choice is most grammatically correct and concise?",
    choices: [
      "NO CHANGE",
      "which they all agreed on",
      "they all agreed on",
      "that they all agreed",
    ],
    correct: 2,
    explanation: "The original is redundant: 'that' already refers to 'decision,' so adding 'it' is ungrammatical. The cleanest fix is 'they all agreed on' as a reduced relative clause. 'Which they all agreed on' is acceptable but choice C is more concise; 'that they all agreed' drops the necessary preposition.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "After studying for hours, Marcus finally felt prepared for the exam <u>scheduled for the following morning</u>.",
    question: "Which choice is most concise without losing essential information?",
    choices: [
      "NO CHANGE",
      "which had been scheduled for the next day morning",
      "that the school had scheduled for the morning that followed",
      "that was scheduled, for the following morning,",
    ],
    correct: 0,
    explanation: "The original is a clean reduced relative clause — 'scheduled for the following morning' is concise and clear. Choice B uses awkward phrasing ('next day morning'); choice C is wordy and roundabout; choice D adds unnecessary commas that turn a tight modifier into a parenthetical.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The novel was longer <u>then</u> any of her previous works, but readers found it just as engaging.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "as",
      "from",
      "than",
    ],
    correct: 3,
    explanation: "'Than' is used for comparisons; 'then' refers to time. 'Longer than' is the correct comparative construction. 'As' would require 'as long as,' and 'from' doesn't pair with 'longer.'",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The scientist presented her findings to the panel, <u>she explained</u> how the results could reshape current theories.",
    question: "Which choice best corrects the sentence boundary?",
    choices: [
      "NO CHANGE",
      "explaining",
      "she explains",
      "and explaining",
    ],
    correct: 1,
    explanation: "The original is a comma splice — two independent clauses joined by only a comma. 'Explaining' turns the second clause into a participial phrase, fixing the splice. 'She explains' shifts tense; 'and explaining' creates a hybrid that doesn't match the first clause's verb form.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "When the storm finally passed, the residents emerged from their homes to assess <u>the damage caused by the high winds and heavy rain</u>.",
    question: "Which choice is most concise?",
    choices: [
      "NO CHANGE",
      "the damage which was caused by the high winds and heavy rain",
      "the damage that the high winds and heavy rain had been the cause of",
      "the damage, and it was caused by high winds and heavy rain",
    ],
    correct: 0,
    explanation: "The reduced relative clause 'caused by the high winds and heavy rain' is concise and clear. Choice B adds unnecessary 'which was'; choice C is wordy and awkward; choice D adds an unnecessary independent clause. Concise reduced relative clauses are preferred when meaning is preserved.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The young chess player, <u>whom many had predicted would lose</u>, advanced to the championship round.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "whom many had predicted losing",
      "who many had predicted to lose",
      "who many had predicted would lose",
    ],
    correct: 3,
    explanation: "The pronoun is the subject of the embedded clause 'would lose,' so the subjective 'who' is correct. The phrase 'many had predicted' is interrupting. 'Whom' would only be correct if the pronoun were an object. Choices B and C shift the verb structure incorrectly.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Although Lila practiced every day, <u>but she still struggled</u> to master the difficult piece.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "yet still she struggled",
      "but still struggling",
      "she still struggled",
    ],
    correct: 3,
    explanation: "'Although' already introduces a contrast clause; pairing it with 'but' is redundant. Just 'she still struggled' works. 'Yet still' double-stacks the contrast. 'But still struggling' creates a fragment.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The journalist's report <u>contained</u> several inaccuracies that the editor needed to correct.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "was containing",
      "is containing",
      "was contain",
    ],
    correct: 0,
    explanation: "Simple past 'contained' is correct for this stative verb describing a past state. State verbs like 'contain' generally don't take progressive aspect, so 'was containing' and 'is containing' are awkward and incorrect. 'Was contain' is ungrammatical.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The mayor announced three new initiatives: <u>improving public transit, more affordable housing, and to invest in parks</u>.",
    question: "Which choice best maintains parallel structure?",
    choices: [
      "NO CHANGE",
      "improving public transit, more affordable housing, and parks investment",
      "improving public transit, expanding affordable housing, and investing in parks",
      "to improve public transit, affordable housing, and parks",
    ],
    correct: 2,
    explanation: "Parallel structure requires each item to share the same form. Choice C uses three '-ing' gerunds: 'improving,' 'expanding,' 'investing.' The original mixes gerund, noun, and infinitive. Choice B mixes gerund and noun phrases; choice D mixes infinitive and bare nouns.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Each of the candidates <u>have</u> submitted their applications by the deadline.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "are having",
      "having",
      "has",
    ],
    correct: 3,
    explanation: "'Each' is singular and takes a singular verb: 'has submitted.' The plural 'candidates' is the object of 'of' and doesn't determine the verb. 'Are having' is plural and progressive; 'having' alone is not a finite verb.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The two friends could not decide <u>between</u> the four restaurants on the block, so they ordered pizza instead.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "among",
      "from amongst",
      "in between",
    ],
    correct: 1,
    explanation: "'Between' is used for two items; 'among' is used for three or more. Since there are four restaurants, 'among' is correct. 'From amongst' is wordy; 'in between' suggests location, not choice.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Having finished her homework early, <u>the television was turned on by Sofia</u> for a half-hour break.",
    question: "Which choice corrects the dangling modifier?",
    choices: [
      "NO CHANGE",
      "the television, turned on by Sofia,",
      "Sofia turned on the television",
      "turning on the television was Sofia's choice",
    ],
    correct: 2,
    explanation: "The opening participial phrase 'Having finished her homework early' must modify the person who finished the homework. Sofia, not the television, finished the homework, so she must be the subject of the main clause. Choice C fixes the modifier. The others leave 'television' or 'turning on' as the subject.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The architect designed a building that was both functional <u>and beautiful</u>, earning her a major award.",
    question: "Which choice best maintains parallelism?",
    choices: [
      "NO CHANGE",
      "as well as having beauty",
      "and also a thing of beauty",
      "and it had beauty",
    ],
    correct: 0,
    explanation: "'Both...and' requires parallel structure. The first item is the adjective 'functional,' so the second must also be an adjective: 'beautiful.' The original is correct. The other choices use noun phrases or clauses, breaking the parallel.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The students gathered in the courtyard <u>because of the fact that</u> the fire alarm had gone off.",
    question: "Which choice is most concise?",
    choices: [
      "NO CHANGE",
      "due to the fact of",
      "because",
      "owing to the fact that",
    ],
    correct: 2,
    explanation: "'Because' alone expresses cause clearly and concisely; 'because of the fact that' is wordy. The other choices are also unnecessarily long versions of 'because.' Strong writing prefers the single word.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The museum's exhibit on ancient Egypt, <u>that opened last month</u>, has already drawn thousands of visitors.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "what opened last month",
      "opened last month",
      "which opened last month",
    ],
    correct: 3,
    explanation: "Nonrestrictive clauses (set off by commas) use 'which,' not 'that.' 'That' is for restrictive clauses without commas. 'What' is incorrect for a relative pronoun here, and 'opened last month' without a relative pronoun creates an awkward fragment within the sentence.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The team played well throughout the season; <u>and they won</u> the championship in a close final match.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "they won",
      "and won",
      "winning",
    ],
    correct: 1,
    explanation: "A semicolon already joins two independent clauses; adding 'and' is redundant. 'They won' alone completes the second clause. 'And won' creates a comma-splice-style hybrid after a semicolon, and 'winning' creates a fragment.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Visitors to the national park are reminded to stay on marked trails, pack out all trash, <u>and respecting wildlife</u> at all times.",
    question: "Which choice best maintains parallelism?",
    choices: [
      "NO CHANGE",
      "and wildlife should be respected",
      "and to respect wildlife",
      "and respect wildlife",
    ],
    correct: 3,
    explanation: "The list uses bare infinitive verbs after 'to': '(to) stay,' '(to) pack,' so the third should be '(to) respect.' Choice D continues the bare-verb pattern. The original uses a gerund; choice B shifts to passive; choice C adds a redundant 'to.'",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The committee will <u>convene at a meeting</u> on Tuesday to review the proposed changes.",
    question: "Which choice is most concise?",
    choices: [
      "NO CHANGE",
      "have a meeting in order to convene",
      "be holding a convening meeting",
      "convene",
    ],
    correct: 3,
    explanation: "'Convene' already means 'to come together for a meeting,' so 'convene at a meeting' is redundant. Just 'convene' is sufficient. The other options pile on extra words without adding meaning.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "Although the new software promised to streamline the workflow, many employees found <u>its interface</u> confusing.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "it's interface",
      "its' interface",
      "their interface",
    ],
    correct: 0,
    explanation: "Possessive 'its' (no apostrophe) is correct — the software owns the interface. 'It's' means 'it is.' 'Its'' is never a valid form. 'Their' would not agree with the singular 'software.' The original is correct.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The orchestra performed beautifully on opening night; <u>moreover, the audience gave a standing ovation</u>.",
    question: "Which choice provides the most logical transition?",
    choices: [
      "NO CHANGE",
      "however, the audience gave a standing ovation",
      "in contrast, the audience gave a standing ovation",
      "despite this, the audience gave a standing ovation",
    ],
    correct: 0,
    explanation: "The second clause adds a positive consequence consistent with the first, so an additive transition like 'moreover' is right. 'However,' 'in contrast,' and 'despite this' all suggest contrast, which doesn't match the logic — a beautiful performance and a standing ovation reinforce each other.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The detective questioned the witness carefully, but neither his answers nor his demeanor <u>were</u> convincing.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "have been",
      "was",
      "is",
    ],
    correct: 2,
    explanation: "With 'neither...nor,' the verb agrees with the closer subject. 'Demeanor' is singular, so the verb must be singular: 'was.' 'Were' and 'have been' are plural; 'is' shifts tense away from the past 'questioned.'",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "By 2025, scientists <u>will have been studying</u> the comet for over a decade, gathering data on its trajectory.",
    question: "Which choice provides the most grammatically correct version of the underlined text?",
    choices: [
      "NO CHANGE",
      "will have studied",
      "have studied",
      "are studying",
    ],
    correct: 0,
    explanation: "Future perfect progressive ('will have been studying') correctly describes an action ongoing up to a point in the future and emphasizes duration ('for over a decade'). 'Have studied' is present perfect and misses the future reference; 'are studying' is simple present progressive; 'will have studied' loses the continuous duration emphasized by 'for over a decade.'",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The new park, which opened to the public last summer, <u>features hiking trails, picnic areas, and a playground that is for children</u>.",
    question: "Which choice is most concise without losing meaning?",
    choices: [
      "NO CHANGE",
      "features hiking trails, picnic areas, and a children's playground",
      "features the following: hiking trails, picnic areas, and also a playground for children",
      "is featuring hiking trails and picnic areas, plus a playground meant for the use of children",
    ],
    correct: 1,
    explanation: "'A children's playground' is more concise than 'a playground that is for children' and preserves meaning. Choice C adds unnecessary phrases like 'the following' and 'also'; choice D is wordy and shifts to progressive aspect.",
  },
  {
    type: "psatRW", subtype: "writingEdit",
    passage: "The hikers stopped at the overlook to admire the view, take photographs, <u>and they rested</u> before continuing the trail.",
    question: "Which choice best maintains parallelism?",
    choices: [
      "NO CHANGE",
      "and resting",
      "and to rest",
      "and rest",
    ],
    correct: 3,
    explanation: "The list uses bare verbs governed by 'to': '(to) admire,' '(to) take,' so the third should be '(to) rest.' Choice D continues the parallel pattern. The original adds a new subject; choice B switches to gerund; choice C adds a redundant 'to.'",
  },
]
