[
  {
    type: "psatMath",
    question: "A right triangle has legs of length 9 and 12. What is the length of the hypotenuse?",
    correct: "15",
    wrong: ["21", "11", "108"],
    explanation: "By the Pythagorean theorem, hypotenuse² = 9² + 12² = 81 + 144 = 225. So hypotenuse = √225 = 15.",
  },
  {
    type: "psatMath",
    question: "A right triangle has legs 8 and 15. What is the length of the hypotenuse?",
    correct: "17",
    wrong: ["23", "13", "120"],
    explanation: "By the Pythagorean theorem, hypotenuse² = 8² + 15² = 64 + 225 = 289. So hypotenuse = √289 = 17.",
  },
  {
    type: "psatMath",
    question: "What is the distance between the points (1, 2) and (4, 6) in the coordinate plane?",
    correct: "5",
    wrong: ["7", "25", "√7"],
    explanation: "Distance = √((4−1)² + (6−2)²) = √(9 + 16) = √25 = 5.",
  },
  {
    type: "psatMath",
    question: "A rectangle has length 14 cm and width 6 cm. What is its perimeter?",
    correct: "40 cm",
    wrong: ["84 cm", "20 cm", "42 cm"],
    explanation: "Perimeter of a rectangle = 2(length + width) = 2(14 + 6) = 2(20) = 40 cm.",
  },
  {
    type: "psatMath",
    question: "A triangle has a base of 10 inches and a height of 7 inches. What is its area?",
    correct: "35 in²",
    wrong: ["70 in²", "17 in²", "140 in²"],
    explanation: "Area of a triangle = ½ × base × height = ½ × 10 × 7 = 35 in².",
  },
  {
    type: "psatMath",
    question: "A circle has a radius of 6. What is its area, in terms of π?",
    correct: "36π",
    wrong: ["12π", "6π", "72π"],
    explanation: "Area of a circle = πr² = π(6²) = 36π.",
  },
  {
    type: "psatMath",
    question: "A circle has a diameter of 10. What is its circumference, in terms of π?",
    correct: "10π",
    wrong: ["5π", "25π", "100π"],
    explanation: "Circumference = π × diameter = 10π. (Alternatively, C = 2πr = 2π(5) = 10π.)",
  },
  {
    type: "psatMath",
    question: "A rectangular box has length 5, width 3, and height 4. What is its volume?",
    correct: "60",
    wrong: ["12", "47", "94"],
    explanation: "Volume of a rectangular box = length × width × height = 5 × 3 × 4 = 60.",
  },
  {
    type: "psatMath",
    question: "A cube has an edge length of 4. What is its surface area?",
    correct: "96",
    wrong: ["64", "16", "24"],
    explanation: "A cube has 6 square faces. Surface area = 6 × (edge)² = 6 × 16 = 96.",
  },
  {
    type: "psatMath",
    question: "A cylinder has radius 3 and height 10. What is its volume, in terms of π?",
    correct: "90π",
    wrong: ["30π", "60π", "300π"],
    explanation: "Volume of a cylinder = πr²h = π(3²)(10) = π(9)(10) = 90π.",
  },
  {
    type: "psatMath",
    question: "Two parallel lines are cut by a transversal. One of the angles formed measures 65°. What is the measure of its corresponding angle?",
    correct: "65°",
    wrong: ["115°", "25°", "180°"],
    explanation: "When parallel lines are cut by a transversal, corresponding angles are congruent. So the corresponding angle also measures 65°.",
  },
  {
    type: "psatMath",
    question: "In a triangle, two angles measure 47° and 68°. What is the measure of the third angle?",
    correct: "65°",
    wrong: ["75°", "115°", "55°"],
    explanation: "Angles in a triangle sum to 180°. Third angle = 180° − 47° − 68° = 65°.",
  },
  {
    type: "psatMath",
    question: "Two angles are vertical angles. One measures (3x + 10)° and the other measures 70°. What is x?",
    correct: "20",
    wrong: ["10", "30", "60"],
    explanation: "Vertical angles are equal. So 3x + 10 = 70, giving 3x = 60, x = 20.",
  },
  {
    type: "psatMath",
    question: "Triangle ABC is similar to triangle DEF. AB = 6, DE = 9. If BC = 8, what is the length of EF?",
    correct: "12",
    wrong: ["10", "11", "16"],
    explanation: "Similar triangles have proportional sides. AB/DE = 6/9 = 2/3, so BC/EF = 2/3. Thus 8/EF = 2/3, giving EF = 24/2 = 12.",
  },
  {
    type: "psatMath",
    question: "In a 45-45-90 right triangle, each leg has length 7. What is the length of the hypotenuse?",
    correct: "7√2",
    wrong: ["14", "7", "49"],
    explanation: "In a 45-45-90 triangle, hypotenuse = leg × √2 = 7√2.",
  },
  {
    type: "psatMath",
    question: "In a 30-60-90 right triangle, the side opposite the 30° angle has length 5. What is the length of the hypotenuse?",
    correct: "10",
    wrong: ["5√3", "5√2", "15"],
    explanation: "In a 30-60-90 triangle, the hypotenuse is twice the shortest side (the one opposite 30°). So hypotenuse = 2 × 5 = 10.",
  },
  {
    type: "psatMath",
    question: "In a right triangle, the side opposite angle A has length 3, and the hypotenuse has length 5. What is sin A?",
    correct: "3/5",
    wrong: ["4/5", "3/4", "5/3"],
    explanation: "sin A = opposite/hypotenuse = 3/5.",
  },
  {
    type: "psatMath",
    question: "In a right triangle, the side adjacent to angle B has length 8 and the hypotenuse has length 10. What is cos B?",
    correct: "4/5",
    wrong: ["3/5", "5/4", "3/4"],
    explanation: "cos B = adjacent/hypotenuse = 8/10 = 4/5.",
  },
  {
    type: "psatMath",
    question: "In a right triangle, the side opposite angle C has length 7 and the adjacent side has length 24. What is tan C?",
    correct: "7/24",
    wrong: ["24/7", "7/25", "24/25"],
    explanation: "tan C = opposite/adjacent = 7/24.",
  },
  {
    type: "psatMath",
    question: "A circle has radius 9. What is its circumference, in terms of π?",
    correct: "18π",
    wrong: ["9π", "81π", "36π"],
    explanation: "Circumference = 2πr = 2π(9) = 18π.",
  },
  {
    type: "psatMath",
    question: "A circle has radius 12. An arc on the circle subtends a central angle of 90°. What is the length of this arc, in terms of π?",
    correct: "6π",
    wrong: ["3π", "12π", "24π"],
    explanation: "Full circumference = 2π(12) = 24π. A 90° arc is 90/360 = 1/4 of the circle. Arc length = (1/4)(24π) = 6π.",
  },
  {
    type: "psatMath",
    question: "A square has a perimeter of 36 cm. What is the area of the square?",
    correct: "81 cm²",
    wrong: ["36 cm²", "324 cm²", "144 cm²"],
    explanation: "Side length = 36/4 = 9 cm. Area = side² = 9² = 81 cm².",
  },
  {
    type: "psatMath",
    question: "A right triangular prism has a triangular base with area 15 and a height (length of prism) of 8. What is the volume of the prism?",
    correct: "120",
    wrong: ["23", "60", "240"],
    explanation: "Volume of a prism = base area × height = 15 × 8 = 120.",
  },
  {
    type: "psatMath",
    question: "Two complementary angles have measures x° and (2x + 9)°. What is x?",
    correct: "27",
    wrong: ["57", "60", "33"],
    explanation: "Complementary angles sum to 90°. So x + 2x + 9 = 90, giving 3x = 81, x = 27.",
  },
  {
    type: "psatMath",
    question: "A 12-foot ladder leans against a wall. Its base is 5 feet from the wall. How high up the wall does the ladder reach?",
    correct: "√119 ft",
    wrong: ["13 ft", "7 ft", "17 ft"],
    explanation: "By the Pythagorean theorem, height² + 5² = 12². So height² = 144 − 25 = 119, height = √119 ft (about 10.9 ft).",
  },
  {
    type: "psatMath",
    question: "What is 35% of 80?",
    correct: "28",
    wrong: ["35", "45", "115"],
    explanation: "35% of 80 = 0.35 × 80 = 28.",
  },
  {
    type: "psatMath",
    question: "A shirt originally costs $40. It is on sale for 25% off. What is the sale price?",
    correct: "$30",
    wrong: ["$15", "$35", "$25"],
    explanation: "25% off means you pay 75% of the original. 0.75 × $40 = $30. (Or: discount is 0.25 × 40 = $10; price = $40 − $10 = $30.)",
  },
  {
    type: "psatMath",
    question: "A population increased from 200 to 250. What is the percent increase?",
    correct: "25%",
    wrong: ["20%", "50%", "5%"],
    explanation: "Percent increase = (new − old)/old × 100% = (250 − 200)/200 × 100% = 50/200 × 100% = 25%.",
  },
  {
    type: "psatMath",
    question: "A laptop costs $600. Sales tax is 8%. What is the total cost including tax?",
    correct: "$648",
    wrong: ["$608", "$680", "$540"],
    explanation: "Tax = 0.08 × $600 = $48. Total = $600 + $48 = $648.",
  },
  {
    type: "psatMath",
    question: "A coat is marked down 20%, then an additional 10% off the sale price. What is the total percent discount from the original price?",
    correct: "28%",
    wrong: ["30%", "25%", "18%"],
    explanation: "After 20% off, you pay 0.80 of the original. After another 10% off, you pay 0.90 × 0.80 = 0.72. So you saved 1 − 0.72 = 0.28 = 28%.",
  },
  {
    type: "psatMath",
    question: "The ratio of boys to girls in a class is 3:5. If there are 24 students total, how many girls are there?",
    correct: "15",
    wrong: ["9", "12", "8"],
    explanation: "Total parts = 3 + 5 = 8. Each part = 24/8 = 3 students. Girls = 5 × 3 = 15.",
  },
  {
    type: "psatMath",
    question: "A recipe uses 2 cups of flour for every 3 cups of milk. If you use 9 cups of milk, how many cups of flour do you need?",
    correct: "6",
    wrong: ["4", "5", "13.5"],
    explanation: "Set up the proportion: 2/3 = x/9. Cross-multiply: 3x = 18, so x = 6 cups of flour.",
  },
  {
    type: "psatMath",
    question: "A bag contains 4 red, 6 blue, and 10 green marbles. If one marble is drawn at random, what is the probability it is blue?",
    correct: "3/10",
    wrong: ["1/5", "1/3", "2/5"],
    explanation: "Total marbles = 4 + 6 + 10 = 20. P(blue) = 6/20 = 3/10.",
  },
  {
    type: "psatMath",
    question: "A fair coin is flipped twice. What is the probability of getting heads both times?",
    correct: "1/4",
    wrong: ["1/2", "1/3", "2/4"],
    explanation: "The flips are independent. P(H and H) = ½ × ½ = 1/4.",
  },
  {
    type: "psatMath",
    question: "A spinner has 5 equal sections numbered 1 through 5. What is the probability of spinning an even number?",
    correct: "2/5",
    wrong: ["1/2", "3/5", "1/5"],
    explanation: "Even numbers on the spinner: 2 and 4 (2 outcomes). Total outcomes: 5. P(even) = 2/5.",
  },
  {
    type: "psatMath",
    question: "The probability of an event is 3/8. What is the probability that the event does NOT occur?",
    correct: "5/8",
    wrong: ["3/8", "1/8", "8/3"],
    explanation: "Complementary events sum to 1. P(not event) = 1 − 3/8 = 5/8.",
  },
  {
    type: "psatMath",
    question: "A class's test scores are 72, 84, 76, 91, 88. What is the median?",
    correct: "84",
    wrong: ["82.2", "76", "88"],
    explanation: "Sort the scores: 72, 76, 84, 88, 91. The middle value (median) is 84.",
  },
  {
    type: "psatMath",
    question: "Find the mean of 12, 15, 18, 20, and 25.",
    correct: "18",
    wrong: ["17", "20", "19"],
    explanation: "Mean = sum/count = (12 + 15 + 18 + 20 + 25)/5 = 90/5 = 18.",
  },
  {
    type: "psatMath",
    question: "What is the mode of the data set 4, 7, 9, 7, 12, 7, 15?",
    correct: "7",
    wrong: ["9", "8.7", "11"],
    explanation: "The mode is the value that appears most often. 7 appears three times — more than any other value.",
  },
  {
    type: "psatMath",
    question: "What is the range of the data set 14, 22, 9, 31, 17, 25?",
    correct: "22",
    wrong: ["9", "31", "20"],
    explanation: "Range = max − min = 31 − 9 = 22.",
  },
  {
    type: "psatMath",
    question: "A car travels 180 miles in 3 hours. What is its average speed in miles per hour?",
    correct: "60 mph",
    wrong: ["540 mph", "183 mph", "30 mph"],
    explanation: "Speed = distance/time = 180/3 = 60 mph.",
  },
  {
    type: "psatMath",
    question: "Maya earns $13.50 per hour. If she works 8 hours, how much does she earn?",
    correct: "$108",
    wrong: ["$104", "$118.50", "$21.50"],
    explanation: "Earnings = rate × time = $13.50 × 8 = $108.",
  },
  {
    type: "psatMath",
    question: "A printer prints 24 pages per minute. How many pages will it print in 15 minutes?",
    correct: "360",
    wrong: ["240", "39", "90"],
    explanation: "Pages = rate × time = 24 × 15 = 360 pages.",
  },
  {
    type: "psatMath",
    question: "Convert 250 centimeters to meters.",
    correct: "2.5 m",
    wrong: ["25 m", "0.25 m", "2500 m"],
    explanation: "1 meter = 100 centimeters. So 250 cm = 250/100 = 2.5 m.",
  },
  {
    type: "psatMath",
    question: "Convert 5 feet to inches.",
    correct: "60 in",
    wrong: ["12 in", "50 in", "72 in"],
    explanation: "1 foot = 12 inches. So 5 ft = 5 × 12 = 60 in.",
  },
  {
    type: "psatMath",
    question: "A phone plan costs $25 per month plus $0.10 per minute. Which equation gives the total monthly cost C in dollars for m minutes?",
    correct: "C = 25 + 0.10m",
    wrong: ["C = 25m + 0.10", "C = 25.10m", "C = 0.10 + 25m"],
    explanation: "Fixed cost $25 plus a per-minute charge of $0.10 times the number of minutes m, giving C = 25 + 0.10m.",
  },
  {
    type: "psatMath",
    question: "A taxi charges a $4 flat fee plus $2 per mile. Sam paid $24 for a ride. How many miles was the ride?",
    correct: "10",
    wrong: ["12", "8", "14"],
    explanation: "Cost = 4 + 2m. Set 4 + 2m = 24. Then 2m = 20, so m = 10 miles.",
  },
  {
    type: "psatMath",
    question: "Three numbers have a mean of 14. Two of the numbers are 11 and 16. What is the third number?",
    correct: "15",
    wrong: ["13", "14", "16"],
    explanation: "Sum of the three = 3 × 14 = 42. Third number = 42 − 11 − 16 = 15.",
  },
  {
    type: "psatMath",
    question: "A right triangle has hypotenuse 13 and one leg of length 5. What is the length of the other leg?",
    correct: "12",
    wrong: ["8", "18", "194"],
    explanation: "By the Pythagorean theorem, leg² + 5² = 13². So leg² = 169 − 25 = 144, leg = 12.",
  },
  {
    type: "psatMath",
    question: "A standard six-sided die is rolled once. What is the probability of rolling a number greater than 4?",
    correct: "1/3",
    wrong: ["1/2", "2/3", "1/6"],
    explanation: "Numbers greater than 4 on a die: 5 and 6 (2 outcomes). Total outcomes: 6. P = 2/6 = 1/3.",
  },
  {
    type: "psatMath",
    question: "A circle has area 49π. What is its radius?",
    correct: "7",
    wrong: ["14", "49", "24.5"],
    explanation: "Area = πr², so πr² = 49π gives r² = 49, r = 7.",
  },
  {
    type: "psatMath",
    question: "An isosceles triangle has two equal angles, each measuring 55°. What is the measure of the third angle?",
    correct: "70°",
    wrong: ["55°", "125°", "90°"],
    explanation: "Angles in a triangle sum to 180°. Third angle = 180° − 55° − 55° = 70°.",
  },
  {
    type: "psatMath",
    question: "The daily high temperatures (°F) for one week were 68, 72, 75, 70, 80, 78, 74. What is the mean, rounded to the nearest tenth?",
    correct: "73.9",
    wrong: ["74.0", "75.0", "72.5"],
    explanation: "Sum = 68 + 72 + 75 + 70 + 80 + 78 + 74 = 517. Mean = 517/7 ≈ 73.857, which rounds to 73.9.",
  },
  {
    type: "psatMath",
    question: "A bag contains 3 red and 5 blue marbles. Two marbles are drawn one at a time WITH replacement. What is the probability both are red?",
    correct: "9/64",
    wrong: ["3/28", "6/16", "3/8"],
    explanation: "Each draw is independent (with replacement). P(red) = 3/8 each time. P(both red) = 3/8 × 3/8 = 9/64.",
  },
  {
    type: "psatMath",
    question: "A rectangular garden is 8 m long and 6 m wide. A walkway 1 m wide surrounds it on all sides. What is the total area of the walkway?",
    correct: "32 m²",
    wrong: ["28 m²", "48 m²", "16 m²"],
    explanation: "Outer rectangle is (8 + 2)(6 + 2) = 10 × 8 = 80 m². Inner garden area = 8 × 6 = 48 m². Walkway = 80 − 48 = 32 m².",
  },
]
