[
  {
    type: "psatMath",
    question: "If 4x − 9 = 23, what is the value of x?",
    correct: "8",
    wrong: ["7", "9", "14"],
    explanation: "Add 9 to both sides: 4x = 32. Divide by 4: x = 8.",
  },
  {
    type: "psatMath",
    question: "Solve for n: 5(n − 3) = 2n + 6.",
    correct: "7",
    wrong: ["3", "5", "9"],
    explanation: "Distribute: 5n − 15 = 2n + 6. Subtract 2n: 3n − 15 = 6. Add 15: 3n = 21. So n = 7.",
  },
  {
    type: "psatMath",
    question: "If 2(x + 4) − 3 = 11, what is x?",
    correct: "3",
    wrong: ["2", "4", "5"],
    explanation: "Distribute: 2x + 8 − 3 = 11, so 2x + 5 = 11. Subtract 5: 2x = 6. Divide by 2: x = 3.",
  },
  {
    type: "psatMath",
    question: "If x/3 + 5 = 11, what is the value of x?",
    correct: "18",
    wrong: ["12", "16", "21"],
    explanation: "Subtract 5: x/3 = 6. Multiply by 3: x = 18.",
  },
  {
    type: "psatMath",
    question: "Solve for y: 7y − 4 = 3y + 16.",
    correct: "5",
    wrong: ["3", "4", "6"],
    explanation: "Subtract 3y: 4y − 4 = 16. Add 4: 4y = 20. So y = 5.",
  },
  {
    type: "psatMath",
    question: "If 0.5x + 1.5 = 4, what is x?",
    correct: "5",
    wrong: ["2.5", "3", "8"],
    explanation: "Subtract 1.5: 0.5x = 2.5. Divide by 0.5: x = 5.",
  },
  {
    type: "psatMath",
    question: "If (2x − 1)/3 = 5, what is the value of x?",
    correct: "8",
    wrong: ["7", "9", "16"],
    explanation: "Multiply both sides by 3: 2x − 1 = 15. Add 1: 2x = 16. So x = 8.",
  },
  {
    type: "psatMath",
    question: "If 6 − 2x = 4x − 12, what is x?",
    correct: "3",
    wrong: ["−3", "2", "6"],
    explanation: "Add 2x to both sides: 6 = 6x − 12. Add 12: 18 = 6x. So x = 3.",
  },
  {
    type: "psatMath",
    question: "Solve for x: 3x/4 = 9.",
    correct: "12",
    wrong: ["6", "9", "27"],
    explanation: "Multiply both sides by 4: 3x = 36. Divide by 3: x = 12.",
  },
  {
    type: "psatMath",
    question: "If 4(2x + 1) = 3(x + 8), what is x?",
    correct: "4",
    wrong: ["2", "3", "5"],
    explanation: "Distribute: 8x + 4 = 3x + 24. Subtract 3x: 5x + 4 = 24. Subtract 4: 5x = 20. So x = 4.",
  },
  {
    type: "psatMath",
    question: "If (x + 2)/5 = (x − 1)/2, what is x?",
    correct: "3",
    wrong: ["−3", "1", "9"],
    explanation: "Cross-multiply: 2(x + 2) = 5(x − 1), so 2x + 4 = 5x − 5. Subtract 2x: 4 = 3x − 5. Add 5: 9 = 3x. So x = 3.",
  },
  {
    type: "psatMath",
    question: "Solve for t: 0.2t − 3 = 1.",
    correct: "20",
    wrong: ["10", "15", "25"],
    explanation: "Add 3: 0.2t = 4. Divide by 0.2: t = 20.",
  },
  {
    type: "psatMath",
    question: "If 3x + 11 = 5x − 7, what is x?",
    correct: "9",
    wrong: ["2", "4", "18"],
    explanation: "Subtract 3x: 11 = 2x − 7. Add 7: 18 = 2x. So x = 9.",
  },
  {
    type: "psatMath",
    question: "If −2(x − 5) = 14, what is x?",
    correct: "−2",
    wrong: ["−12", "2", "12"],
    explanation: "Distribute: −2x + 10 = 14. Subtract 10: −2x = 4. Divide by −2: x = −2.",
  },
  {
    type: "psatMath",
    question: "If x + 1/2 = 7/4, what is x?",
    correct: "5/4",
    wrong: ["1/2", "3/4", "9/4"],
    explanation: "Subtract 1/2 (which is 2/4) from 7/4: x = 7/4 − 2/4 = 5/4.",
  },
  {
    type: "psatMath",
    question: "Solve for x: 8 − (x + 3) = 2x − 1.",
    correct: "2",
    wrong: ["1", "3", "4"],
    explanation: "Distribute the negative: 8 − x − 3 = 2x − 1, so 5 − x = 2x − 1. Add x: 5 = 3x − 1. Add 1: 6 = 3x. So x = 2.",
  },
  {
    type: "psatMath",
    question: "If 5x − 3 = 2(x + 6), what is x?",
    correct: "5",
    wrong: ["3", "4", "6"],
    explanation: "Distribute: 5x − 3 = 2x + 12. Subtract 2x: 3x − 3 = 12. Add 3: 3x = 15. So x = 5.",
  },
  {
    type: "psatMath",
    question: "If 2/3 x = 10, what is x?",
    correct: "15",
    wrong: ["20/3", "20", "30"],
    explanation: "Multiply both sides by 3/2: x = 10 × 3/2 = 30/2 = 15.",
  },
  {
    type: "psatMath",
    question: "If 7 − 3x = −8, what is x?",
    correct: "5",
    wrong: ["−5", "1/3", "15"],
    explanation: "Subtract 7: −3x = −15. Divide by −3: x = 5.",
  },
  {
    type: "psatMath",
    question: "Three more than twice a number equals 17. What is the number?",
    correct: "7",
    wrong: ["5", "8", "10"],
    explanation: "Let n be the number: 2n + 3 = 17. Subtract 3: 2n = 14. So n = 7.",
  },
  {
    type: "psatMath",
    question: "If x + y = 10 and x − y = 4, what is x?",
    correct: "7",
    wrong: ["3", "5", "6"],
    explanation: "Add the equations: 2x = 14, so x = 7. (Then y = 3.)",
  },
  {
    type: "psatMath",
    question: "If 2x + y = 11 and x − y = 1, what is x?",
    correct: "4",
    wrong: ["3", "5", "7"],
    explanation: "Add the equations: 3x = 12, so x = 4. (Then y = 3.)",
  },
  {
    type: "psatMath",
    question: "If y = 2x − 1 and y = x + 4, what is the value of x?",
    correct: "5",
    wrong: ["3", "4", "9"],
    explanation: "Set equal: 2x − 1 = x + 4. Subtract x: x − 1 = 4. So x = 5.",
  },
  {
    type: "psatMath",
    question: "Solve the system: 3x + 2y = 16 and x = y + 2. What is y?",
    correct: "2",
    wrong: ["4", "5", "6"],
    explanation: "Substitute x = y + 2 into the first equation: 3(y + 2) + 2y = 16, so 5y + 6 = 16. Subtract 6: 5y = 10. So y = 2.",
  },
  {
    type: "psatMath",
    question: "If x + 2y = 9 and 3x − y = 13, what is x?",
    correct: "5",
    wrong: ["2", "3", "4"],
    explanation: "From the second equation, y = 3x − 13. Substitute: x + 2(3x − 13) = 9, so 7x − 26 = 9. Add 26: 7x = 35. So x = 5.",
  },
  {
    type: "psatMath",
    question: "If 4x + 3y = 26 and 2x − 3y = 4, what is x?",
    correct: "5",
    wrong: ["3", "4", "6"],
    explanation: "Add the equations to eliminate y: 6x = 30, so x = 5.",
  },
  {
    type: "psatMath",
    question: "If 2x + 5y = 20 and x = 3y − 1, what is y?",
    correct: "2",
    wrong: ["1", "3", "4"],
    explanation: "Substitute x = 3y − 1 into the first equation: 2(3y − 1) + 5y = 20, so 6y − 2 + 5y = 20, i.e. 11y − 2 = 20. Add 2: 11y = 22. So y = 2.",
  },
  {
    type: "psatMath",
    question: "If a + b = 12 and 2a − b = 9, what is a?",
    correct: "7",
    wrong: ["3", "5", "6"],
    explanation: "Add the equations: 3a = 21, so a = 7. (Then b = 5.)",
  },
  {
    type: "psatMath",
    question: "If 5x − 2y = 16 and 3x + 2y = 16, what is x?",
    correct: "4",
    wrong: ["2", "3", "8"],
    explanation: "Add the equations: 8x = 32, so x = 4.",
  },
  {
    type: "psatMath",
    question: "If x + y = 7 and 2x + 3y = 17, what is the value of y?",
    correct: "3",
    wrong: ["2", "4", "5"],
    explanation: "From the first equation, x = 7 − y. Substitute: 2(7 − y) + 3y = 17, so 14 + y = 17. Subtract 14: y = 3.",
  },
  {
    type: "psatMath",
    question: "Solve the system: y = 3x + 1 and 2x + y = 11. What ordered pair (x, y) satisfies both?",
    correct: "(2, 7)",
    wrong: ["(1, 4)", "(3, 10)", "(2, 5)"],
    explanation: "Substitute: 2x + (3x + 1) = 11, so 5x + 1 = 11, x = 2. Then y = 3(2) + 1 = 7. So (2, 7).",
  },
  {
    type: "psatMath",
    question: "If x > 5, which of the following must also be true?",
    correct: "2x > 10",
    wrong: ["x > 10", "x < 5", "x = 5"],
    explanation: "Multiplying both sides of x > 5 by 2 (positive) preserves the inequality: 2x > 10.",
  },
  {
    type: "psatMath",
    question: "Solve for x: 3x − 4 > 11.",
    correct: "x > 5",
    wrong: ["x > 7/3", "x > 15", "x < 5"],
    explanation: "Add 4: 3x > 15. Divide by 3: x > 5.",
  },
  {
    type: "psatMath",
    question: "Solve for x: −2x + 5 ≥ 1.",
    correct: "x ≤ 2",
    wrong: ["x ≥ 2", "x ≤ −2", "x ≥ 3"],
    explanation: "Subtract 5: −2x ≥ −4. Divide by −2 and flip the inequality: x ≤ 2.",
  },
  {
    type: "psatMath",
    question: "Solve for x: 4(x − 1) < 2x + 6.",
    correct: "x < 5",
    wrong: ["x > 5", "x < 2", "x < 10"],
    explanation: "Distribute: 4x − 4 < 2x + 6. Subtract 2x: 2x − 4 < 6. Add 4: 2x < 10. Divide by 2: x < 5.",
  },
  {
    type: "psatMath",
    question: "If −3x ≤ 12, what is the solution?",
    correct: "x ≥ −4",
    wrong: ["x ≤ −4", "x ≥ 4", "x ≤ 4"],
    explanation: "Divide both sides by −3 and flip the inequality: x ≥ −4.",
  },
  {
    type: "psatMath",
    question: "Solve for n: 5n + 3 ≤ 2n + 18.",
    correct: "n ≤ 5",
    wrong: ["n ≥ 5", "n ≤ 7", "n ≤ 3"],
    explanation: "Subtract 2n: 3n + 3 ≤ 18. Subtract 3: 3n ≤ 15. So n ≤ 5.",
  },
  {
    type: "psatMath",
    question: "Which value of x satisfies x − 7 > 2?",
    correct: "10",
    wrong: ["5", "7", "9"],
    explanation: "x − 7 > 2 means x > 9. Only 10 is greater than 9.",
  },
  {
    type: "psatMath",
    question: "Solve for x: (x + 3)/2 ≥ 5.",
    correct: "x ≥ 7",
    wrong: ["x ≥ 10", "x ≥ 4", "x ≤ 7"],
    explanation: "Multiply both sides by 2: x + 3 ≥ 10. Subtract 3: x ≥ 7.",
  },
  {
    type: "psatMath",
    question: "If 2 < x < 7 and x is an integer, how many possible values of x are there?",
    correct: "4",
    wrong: ["3", "5", "6"],
    explanation: "The integers strictly between 2 and 7 are 3, 4, 5, and 6 — that's 4 values.",
  },
  {
    type: "psatMath",
    question: "Solve for x: 6 − 2x < 14.",
    correct: "x > −4",
    wrong: ["x < −4", "x > 4", "x < 4"],
    explanation: "Subtract 6: −2x < 8. Divide by −2 and flip: x > −4.",
  },
  {
    type: "psatMath",
    question: "If x ≥ 3 and x ≤ 8, which interval describes x?",
    correct: "3 ≤ x ≤ 8",
    wrong: ["3 < x < 8", "x ≥ 3", "x ≤ 8"],
    explanation: "Both endpoints are included (≥ and ≤), so the combined interval is 3 ≤ x ≤ 8.",
  },
  {
    type: "psatMath",
    question: "If |x| = 7, what are all possible values of x?",
    correct: "7 and −7",
    wrong: ["7 only", "−7 only", "0 and 7"],
    explanation: "Absolute value measures distance from 0. Both 7 and −7 are 7 units from 0.",
  },
  {
    type: "psatMath",
    question: "If |x − 3| = 5, what are the possible values of x?",
    correct: "8 and −2",
    wrong: ["8 and 2", "−8 and 2", "5 and −5"],
    explanation: "Either x − 3 = 5 (giving x = 8) or x − 3 = −5 (giving x = −2).",
  },
  {
    type: "psatMath",
    question: "If |2x + 1| = 9, what is the positive value of x?",
    correct: "4",
    wrong: ["5", "8", "9/2"],
    explanation: "Either 2x + 1 = 9 (so x = 4) or 2x + 1 = −9 (so x = −5). The positive value is 4.",
  },
  {
    type: "psatMath",
    question: "If |x + 4| = 0, what is x?",
    correct: "−4",
    wrong: ["0", "4", "no solution"],
    explanation: "Absolute value equals 0 only when the inside equals 0: x + 4 = 0, so x = −4.",
  },
  {
    type: "psatMath",
    question: "How many solutions does |x − 2| = −3 have?",
    correct: "0",
    wrong: ["1", "2", "infinitely many"],
    explanation: "Absolute value is never negative, so |x − 2| = −3 has no solutions.",
  },
  {
    type: "psatMath",
    question: "If f(x) = 3x − 5, what is f(4)?",
    correct: "7",
    wrong: ["2", "12", "17"],
    explanation: "f(4) = 3(4) − 5 = 12 − 5 = 7.",
  },
  {
    type: "psatMath",
    question: "If f(x) = x² + 2x, what is f(−3)?",
    correct: "3",
    wrong: ["−3", "9", "15"],
    explanation: "f(−3) = (−3)² + 2(−3) = 9 − 6 = 3.",
  },
  {
    type: "psatMath",
    question: "If g(x) = 2x + 1, what is g(g(2))?",
    correct: "11",
    wrong: ["5", "9", "13"],
    explanation: "First, g(2) = 2(2) + 1 = 5. Then g(5) = 2(5) + 1 = 11.",
  },
  {
    type: "psatMath",
    question: "If f(x) = x − 4 and g(x) = 2x, what is f(g(3))?",
    correct: "2",
    wrong: ["−2", "5", "6"],
    explanation: "g(3) = 2(3) = 6. Then f(6) = 6 − 4 = 2.",
  },
  {
    type: "psatMath",
    question: "If h(x) = 4 − x², what is h(−2)?",
    correct: "0",
    wrong: ["−4", "4", "8"],
    explanation: "h(−2) = 4 − (−2)² = 4 − 4 = 0.",
  },
  {
    type: "psatMath",
    question: "If f(x) = 5 − 2x, for what value of x does f(x) = 1?",
    correct: "2",
    wrong: ["−2", "3", "7/2"],
    explanation: "Set 5 − 2x = 1. Subtract 5: −2x = −4. So x = 2.",
  },
  {
    type: "psatMath",
    question: "If f(x) = (x + 1)/(x − 2), what value of x is NOT in the domain?",
    correct: "2",
    wrong: ["−1", "0", "1"],
    explanation: "The denominator x − 2 must not equal 0, so x ≠ 2.",
  },
  {
    type: "psatMath",
    question: "If f(x) = x² and g(x) = x + 3, what is g(f(2))?",
    correct: "7",
    wrong: ["5", "11", "25"],
    explanation: "f(2) = 2² = 4. Then g(4) = 4 + 3 = 7.",
  },
  {
    type: "psatMath",
    question: "If f(x) = 2x + 1, what does the graph of f(x) + 3 look like compared to f(x)?",
    correct: "shifted up 3 units",
    wrong: ["shifted down 3 units", "shifted left 3 units", "shifted right 3 units"],
    explanation: "Adding a constant outside the function shifts the graph vertically. f(x) + 3 shifts up 3.",
  },
  {
    type: "psatMath",
    question: "If f(x) = x², what does the graph of f(x − 2) look like compared to f(x)?",
    correct: "shifted right 2 units",
    wrong: ["shifted left 2 units", "shifted up 2 units", "shifted down 2 units"],
    explanation: "Replacing x with x − 2 shifts the graph horizontally to the right by 2.",
  },
  {
    type: "psatMath",
    question: "If f(x) = 3x and g(x) = x − 4, what is f(g(5))?",
    correct: "3",
    wrong: ["1", "11", "15"],
    explanation: "g(5) = 5 − 4 = 1. Then f(1) = 3(1) = 3.",
  },
  {
    type: "psatMath",
    question: "What are the solutions to x² − 5x + 6 = 0?",
    correct: "2 and 3",
    wrong: ["−2 and −3", "1 and 6", "−1 and 6"],
    explanation: "Factor: (x − 2)(x − 3) = 0. So x = 2 or x = 3.",
  },
  {
    type: "psatMath",
    question: "What are the solutions to x² − 9 = 0?",
    correct: "3 and −3",
    wrong: ["3 only", "9 and −9", "0 and 9"],
    explanation: "Factor as a difference of squares: (x − 3)(x + 3) = 0. So x = 3 or x = −3.",
  },
  {
    type: "psatMath",
    question: "What is the vertex of the parabola y = (x − 4)² + 1?",
    correct: "(4, 1)",
    wrong: ["(−4, 1)", "(4, −1)", "(1, 4)"],
    explanation: "In vertex form y = (x − h)² + k, the vertex is (h, k). Here h = 4 and k = 1, so the vertex is (4, 1).",
  },
  {
    type: "psatMath",
    question: "What are the solutions to x² + 2x − 8 = 0?",
    correct: "2 and −4",
    wrong: ["−2 and 4", "−2 and −4", "2 and 4"],
    explanation: "Factor: (x + 4)(x − 2) = 0. So x = −4 or x = 2.",
  },
  {
    type: "psatMath",
    question: "If x² = 49, what are the possible values of x?",
    correct: "7 and −7",
    wrong: ["7 only", "−7 only", "0 and 7"],
    explanation: "Taking the square root of both sides gives x = ±7, so x = 7 or x = −7.",
  },
  {
    type: "psatMath",
    question: "A population of bacteria doubles every hour. If there are 50 bacteria at the start, how many are there after 3 hours?",
    correct: "400",
    wrong: ["150", "300", "800"],
    explanation: "After each hour, multiply by 2. After 3 hours: 50 × 2³ = 50 × 8 = 400.",
  },
  {
    type: "psatMath",
    question: "If y = 3 · 2ˣ, what is y when x = 4?",
    correct: "48",
    wrong: ["24", "32", "64"],
    explanation: "y = 3 · 2⁴ = 3 · 16 = 48.",
  },
  {
    type: "psatMath",
    question: "A car's value drops by half every 4 years. If it is worth $20,000 today, what will it be worth in 8 years?",
    correct: "$5,000",
    wrong: ["$2,500", "$10,000", "$15,000"],
    explanation: "After 4 years: $20,000 / 2 = $10,000. After 8 years (another halving): $10,000 / 2 = $5,000.",
  },
  {
    type: "psatMath",
    question: "If f(x) = 5 · 3ˣ, what is f(0)?",
    correct: "5",
    wrong: ["0", "1", "15"],
    explanation: "Any nonzero number to the 0 power is 1, so f(0) = 5 · 3⁰ = 5 · 1 = 5.",
  },
  {
    type: "psatMath",
    question: "An investment grows by 10% each year. Which expression gives the value after t years if it starts at $500?",
    correct: "500(1.10)ᵗ",
    wrong: ["500(0.10)ᵗ", "500 + 0.10t", "500(1.10)t"],
    explanation: "Exponential growth uses the form a(1 + r)ᵗ where r = 0.10, so the expression is 500(1.10)ᵗ.",
  },
]
