[
  {
    type: "psatRW", subtype: "vocab",
    passage: "After months of rumors, the company's CEO finally gave a candid interview, openly admitting mistakes the board had tried to hide. Reporters were stunned by her willingness to say so much.",
    question: "As used in the passage, 'candid' most nearly means:",
    choices: ["photographed", "cheerful", "biased", "frank"],
    correct: 3,
    explanation: "The CEO 'openly admits' mistakes — she is being frank. 'Photographed' is a common literal meaning (candid photo) but doesn't fit; 'cheerful' and 'biased' miss the sense of honesty.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Although the new manager hoped to mitigate the team's frustration, the long hours and shrinking budget made any real relief difficult.",
    question: "As used in the passage, 'mitigate' most nearly means:",
    choices: ["increase", "ease", "explain", "ignore"],
    correct: 1,
    explanation: "The manager wants 'relief' from frustration — to make it less severe. 'Increase' is the opposite; 'explain' and 'ignore' don't fit the idea of softening a problem.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The applause was tepid — a few polite claps scattered through the auditorium, and then silence. The performer left the stage looking deflated.",
    question: "As used in the passage, 'tepid' most nearly means:",
    choices: ["thunderous", "warm", "lukewarm", "hostile"],
    correct: 2,
    explanation: "'A few polite claps' shows weak, unenthusiastic applause. 'Lukewarm' captures that. 'Warm' is the literal temperature meaning but suggests genuine approval; 'thunderous' is the opposite; 'hostile' is too strong.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Beauty in fashion is famously ephemeral; a style that dominates one season is forgotten by the next.",
    question: "As used in the passage, 'ephemeral' most nearly means:",
    choices: ["expensive", "popular", "complicated", "short-lived"],
    correct: 3,
    explanation: "A style that vanishes in a season is fleeting. 'Short-lived' fits. 'Popular' is true of the style but isn't the meaning of the word; 'expensive' and 'complicated' don't fit at all.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Maya felt ambivalent about the move: she was excited to start a new school but heartbroken to leave her friends behind.",
    question: "As used in the passage, 'ambivalent' most nearly means:",
    choices: ["conflicted", "furious", "uninterested", "thrilled"],
    correct: 0,
    explanation: "She has both positive and negative feelings — that's the definition of conflicted. 'Uninterested' is wrong because she clearly feels strongly; 'furious' and 'thrilled' each capture only one side.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The report was admirably succinct: three pages summarized findings that earlier drafts had spread across thirty.",
    question: "As used in the passage, 'succinct' most nearly means:",
    choices: ["accurate", "boring", "brief", "official"],
    correct: 2,
    explanation: "Three pages instead of thirty — the report is short and to the point. 'Brief' fits. 'Accurate' and 'official' may be true but aren't the meaning; 'boring' has the wrong tone (admiring, not critical).",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "A scrupulous accountant, Mr. Patel checked every receipt twice and refused to round any figure, even by a penny.",
    question: "As used in the passage, 'scrupulous' most nearly means:",
    choices: ["wealthy", "suspicious", "slow", "careful"],
    correct: 3,
    explanation: "Checking everything twice shows extreme care. 'Careful' fits. 'Slow' might result from his habits but isn't the meaning; 'wealthy' and 'suspicious' are unrelated.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The senator delivered a vehement defense of the bill, pounding the podium and raising her voice until the chamber fell silent.",
    question: "As used in the passage, 'vehement' most nearly means:",
    choices: ["confused", "passionate", "quiet", "lengthy"],
    correct: 1,
    explanation: "Pounding the podium and raising her voice show intense feeling. 'Passionate' fits. 'Quiet' is the opposite; 'lengthy' and 'confused' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Rather than chase a glamorous lawsuit, the firm took a pragmatic approach and settled out of court, saving years of expense.",
    question: "As used in the passage, 'pragmatic' most nearly means:",
    choices: ["practical", "cowardly", "creative", "secretive"],
    correct: 0,
    explanation: "Settling to save time and money is a practical choice. 'Practical' fits. 'Cowardly' adds a negative judgment the passage doesn't; 'creative' and 'secretive' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Despite a deluge of criticism, the coach remained resolute, insisting the team would not change its strategy mid-season.",
    question: "As used in the passage, 'resolute' most nearly means:",
    choices: ["confused", "polite", "determined", "angry"],
    correct: 2,
    explanation: "He won't change course despite criticism — he's firm in his decision. 'Determined' fits. 'Angry' might be a reaction but isn't the meaning; 'confused' is the opposite; 'polite' is unrelated.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "When the referee reversed the call, the crowd grew indignant, booing for nearly a full minute.",
    question: "As used in the passage, 'indignant' most nearly means:",
    choices: ["sleepy", "outraged", "amused", "embarrassed"],
    correct: 1,
    explanation: "Booing for a full minute shows strong anger at perceived injustice. 'Outraged' fits. 'Amused' is the opposite; 'sleepy' and 'embarrassed' don't fit.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The young intern was unfailingly deferential to senior partners, never interrupting and always asking permission before speaking.",
    question: "As used in the passage, 'deferential' most nearly means:",
    choices: ["ambitious", "rude", "talkative", "respectful"],
    correct: 3,
    explanation: "Not interrupting and asking permission show respect for rank. 'Respectful' fits. 'Rude' and 'talkative' are the opposite; 'ambitious' may describe an intern but isn't the meaning here.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "In a magnanimous gesture, the winning candidate invited her former rival to join the transition team.",
    question: "As used in the passage, 'magnanimous' most nearly means:",
    choices: ["public", "generous", "calculated", "reluctant"],
    correct: 1,
    explanation: "Welcoming a defeated rival shows largeness of spirit. 'Generous' fits. 'Calculated' suggests a strategic motive not in the passage; 'reluctant' is the opposite; 'public' describes the act but not the word.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The new tariffs threatened to exacerbate the supply shortage, making goods even scarcer than they had been all year.",
    question: "As used in the passage, 'exacerbate' most nearly means:",
    choices: ["worsen", "explain", "delay", "solve"],
    correct: 0,
    explanation: "Goods will become 'even scarcer' — the problem grows worse. 'Worsen' fits. 'Solve' is the opposite; 'explain' and 'delay' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "A prolific writer, she had published twenty-three novels by the time most authors finished their first.",
    question: "As used in the passage, 'prolific' most nearly means:",
    choices: ["famous", "productive", "wealthy", "elderly"],
    correct: 1,
    explanation: "Twenty-three novels means producing a lot of work. 'Productive' fits. 'Famous' and 'wealthy' may follow from being prolific but aren't the meaning; 'elderly' is unsupported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The judge's judicious handling of the case — weighing each motion carefully, refusing to be rushed — earned praise from both sides.",
    question: "As used in the passage, 'judicious' most nearly means:",
    choices: ["slow", "harsh", "predictable", "wise"],
    correct: 3,
    explanation: "Weighing motions carefully and refusing to rush show good judgment. 'Wise' fits. 'Slow' describes pace, not wisdom; 'harsh' and 'predictable' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Although the disease showed no symptoms at first, the virus remained latent in the body, waiting for the immune system to weaken.",
    question: "As used in the passage, 'latent' most nearly means:",
    choices: ["deadly", "hidden", "spreading", "harmless"],
    correct: 1,
    explanation: "The virus is present but produces no symptoms — it's dormant and unseen. 'Hidden' fits. 'Spreading' contradicts the no-symptoms idea; 'deadly' and 'harmless' aren't the meaning.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Her approach to the problem was genuinely novel: no one in the lab had ever tried combining the two techniques before.",
    question: "As used in the passage, 'novel' most nearly means:",
    choices: ["fictional", "complicated", "fresh", "lengthy"],
    correct: 2,
    explanation: "No one had tried it before — the approach is new. 'Fresh' fits. 'Fictional' is the common noun meaning (a novel = a book) but doesn't apply here; 'complicated' and 'lengthy' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "He was a staid figure in a flashy industry, wearing the same gray suit and giving the same measured speeches year after year.",
    question: "As used in the passage, 'staid' most nearly means:",
    choices: ["wealthy", "dishonest", "creative", "sober"],
    correct: 3,
    explanation: "The same gray suit and measured speeches show a serious, unflashy character. 'Sober' (in the sense of restrained) fits. 'Creative' is the opposite; 'wealthy' and 'dishonest' are unsupported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The committee meeting grew contentious, with members shouting over one another and one storming out before the vote.",
    question: "As used in the passage, 'contentious' most nearly means:",
    choices: ["productive", "argumentative", "quiet", "brief"],
    correct: 1,
    explanation: "Shouting and storming out show heated argument. 'Argumentative' fits. 'Quiet' and 'productive' are the opposite; 'brief' isn't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "There were copious notes in the margins of the textbook — sometimes three or four colors per page, plus diagrams and arrows.",
    question: "As used in the passage, 'copious' most nearly means:",
    choices: ["colorful", "abundant", "scattered", "neat"],
    correct: 1,
    explanation: "Three or four colors per page plus diagrams means lots of notes. 'Abundant' fits. 'Colorful' is true but describes a different feature; 'scattered' and 'neat' don't match the idea of quantity.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The lecturer's discussion of medieval coinage was so esoteric that even graduate students struggled to follow it.",
    question: "As used in the passage, 'esoteric' most nearly means:",
    choices: ["boring", "obscure", "controversial", "ancient"],
    correct: 1,
    explanation: "Even graduate students couldn't follow it — the material is understood only by specialists. 'Obscure' fits. 'Ancient' describes the topic but not the word; 'boring' and 'controversial' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Aiming for a conciliatory tone, the principal apologized for the misunderstanding and offered to meet with parents individually.",
    question: "As used in the passage, 'conciliatory' most nearly means:",
    choices: ["aggressive", "official", "soothing", "formal"],
    correct: 2,
    explanation: "Apologizing and offering personal meetings is meant to calm anger. 'Soothing' fits. 'Aggressive' is the opposite; 'official' and 'formal' miss the peacemaking intent.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The mansion's conspicuous wealth — gold-leaf gates, marble fountains, a fleet of imported cars — drew stares from every passing tourist.",
    question: "As used in the passage, 'conspicuous' most nearly means:",
    choices: ["obvious", "tasteful", "hidden", "imaginary"],
    correct: 0,
    explanation: "Gold gates and marble fountains are impossible to miss. 'Obvious' fits. 'Hidden' is the opposite; 'tasteful' is a judgment the passage doesn't support; 'imaginary' contradicts the description.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "When pressed about his plans, the politician began to equivocate, offering long answers that committed to nothing.",
    question: "As used in the passage, 'equivocate' most nearly means:",
    choices: ["dodge", "shout", "agree", "explain"],
    correct: 0,
    explanation: "Long answers committing to nothing means avoiding a clear answer. 'Dodge' fits. 'Agree' and 'explain' would require clarity; 'shout' is unrelated.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "A fastidious dresser, Diego pressed every shirt the night before and refused to leave the house with a single hair out of place.",
    question: "As used in the passage, 'fastidious' most nearly means:",
    choices: ["stylish", "anxious", "wealthy", "meticulous"],
    correct: 3,
    explanation: "Pressing shirts nightly and tolerating no stray hair shows attention to detail. 'Meticulous' fits. 'Stylish' may be a result but isn't the meaning; 'anxious' and 'wealthy' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The laws of arithmetic are essentially immutable: two plus two has equaled four in every century and culture.",
    question: "As used in the passage, 'immutable' most nearly means:",
    choices: ["unchanging", "complicated", "useful", "ancient"],
    correct: 0,
    explanation: "The same answer in every century shows the laws don't change. 'Unchanging' fits. 'Ancient' describes age, not the quality of being fixed; 'useful' and 'complicated' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Most days at the office were mundane — answering emails, refilling the printer, ordering lunch — and Priya longed for something more interesting.",
    question: "As used in the passage, 'mundane' most nearly means:",
    choices: ["ordinary", "stressful", "global", "secretive"],
    correct: 0,
    explanation: "Emails and printer refills are everyday tasks. 'Ordinary' fits. 'Global' (the other dictionary sense — worldly) doesn't fit here; 'stressful' and 'secretive' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Although the action took place at the center of the city, the novel's main character lived a peripheral life, watching events unfold from the edges.",
    question: "As used in the passage, 'peripheral' most nearly means:",
    choices: ["digital", "wealthy", "marginal", "exciting"],
    correct: 2,
    explanation: "He watches from the edges, not the center. 'Marginal' fits. 'Digital' is a computer-hardware sense (peripherals) that doesn't apply; 'exciting' is the opposite; 'wealthy' is unrelated.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Even after losing the regional final, the team remained sanguine, certain they would return stronger next season.",
    question: "As used in the passage, 'sanguine' most nearly means:",
    choices: ["bloody", "exhausted", "optimistic", "bitter"],
    correct: 2,
    explanation: "Believing they'll return stronger shows cheerful confidence. 'Optimistic' fits. 'Bloody' is the literal Latin meaning but doesn't fit; 'bitter' and 'exhausted' are the opposite tone.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Even as the storm shattered windows and tore off roof tiles, the lighthouse keeper remained stoic, calmly recording wind speeds in his logbook.",
    question: "As used in the passage, 'stoic' most nearly means:",
    choices: ["impassive", "frightened", "clever", "religious"],
    correct: 0,
    explanation: "Calmly recording data during a storm shows lack of visible emotion. 'Impassive' fits. 'Frightened' is the opposite reaction; 'clever' and 'religious' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "His grandfather was taciturn at dinner, answering questions in a single word and leaving long silences between them.",
    question: "As used in the passage, 'taciturn' most nearly means:",
    choices: ["cheerful", "rude", "reserved", "elderly"],
    correct: 2,
    explanation: "Single-word answers and long silences show someone who speaks little. 'Reserved' fits. 'Rude' adds a judgment not in the passage; 'cheerful' is the wrong tone; 'elderly' describes the grandfather but isn't the meaning.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The senator continued to vacillate on the bill, supporting it Monday, opposing it Wednesday, and refusing to comment on Friday.",
    question: "As used in the passage, 'vacillate' most nearly means:",
    choices: ["waver", "complain", "lie", "promise"],
    correct: 0,
    explanation: "Switching from support to opposition to silence shows shifting back and forth. 'Waver' fits. 'Lie' adds an accusation the passage doesn't; 'complain' and 'promise' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The biographer wrote with a reverence bordering on worship; every chapter described the inventor's choices as faultless.",
    question: "As used in the passage, 'reverence' most nearly means:",
    choices: ["humor", "boredom", "awe", "anger"],
    correct: 2,
    explanation: "Treating someone's choices as faultless reflects deep respect. 'Awe' fits. 'Anger' is the opposite; 'humor' and 'boredom' don't match the worshipful tone.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Although the company claimed a renaissance, the actual sales figures showed only a tenuous recovery — small gains that any setback could erase.",
    question: "As used in the passage, 'tenuous' most nearly means:",
    choices: ["fraudulent", "weak", "rapid", "permanent"],
    correct: 1,
    explanation: "A recovery that any setback could erase is fragile. 'Weak' fits. 'Permanent' is the opposite; 'fraudulent' adds dishonesty not in the passage; 'rapid' doesn't match either.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The mayor's speech was so verbose that listeners had stopped paying attention long before he reached his actual proposal.",
    question: "As used in the passage, 'verbose' most nearly means:",
    choices: ["honest", "loud", "dull", "wordy"],
    correct: 3,
    explanation: "Listeners tune out before he reaches the point because he uses too many words. 'Wordy' fits. 'Dull' might be a result but isn't the meaning; 'honest' and 'loud' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Trust, once shattered, is difficult to mend; even the most earnest apology cannot always restore it.",
    question: "As used in the passage, 'earnest' most nearly means:",
    choices: ["public", "lengthy", "sincere", "rehearsed"],
    correct: 2,
    explanation: "An apology that 'cannot always restore' trust is genuine but still falls short. 'Sincere' fits. 'Rehearsed' would suggest the opposite; 'public' and 'lengthy' aren't the meaning.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The volunteer's gesture was unexpectedly poignant: a single handwritten letter that reminded the patient of his mother's letters from forty years before.",
    question: "As used in the passage, 'poignant' most nearly means:",
    choices: ["humorous", "moving", "expensive", "brief"],
    correct: 1,
    explanation: "Reminding someone of long-lost letters from a parent stirs emotion. 'Moving' fits. 'Brief' may describe the letter but isn't the meaning; 'humorous' is the wrong tone; 'expensive' is unrelated.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Once a quaint fishing village, the town had become a sprawling resort, with hotels stretching for miles along what had been bare coastline.",
    question: "As used in the passage, 'sprawling' most nearly means:",
    choices: ["wealthy", "lazy", "expansive", "ruined"],
    correct: 2,
    explanation: "Hotels for miles along formerly bare coast means spread out over a wide area. 'Expansive' fits. 'Lazy' is the other sense (sprawled on a couch) but doesn't fit; 'wealthy' and 'ruined' aren't the meaning.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The diplomat was known for her astute reading of opponents; she could spot a bluff across the negotiating table within minutes.",
    question: "As used in the passage, 'astute' most nearly means:",
    choices: ["perceptive", "ruthless", "polite", "talkative"],
    correct: 0,
    explanation: "Spotting a bluff quickly shows sharp insight. 'Perceptive' fits. 'Ruthless' adds an aggressive quality the passage doesn't; 'polite' and 'talkative' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Rather than punish the rookie's mistake, the captain was lenient, asking only that she review the manual and return to duty the next morning.",
    question: "As used in the passage, 'lenient' most nearly means:",
    choices: ["forgetful", "merciful", "strict", "confused"],
    correct: 1,
    explanation: "Asking only for review rather than punishment shows mildness in discipline. 'Merciful' fits. 'Strict' is the opposite; 'forgetful' and 'confused' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Although the gallery owners were skeptical at first, the young painter's bold work eventually won universal acclaim, with critics calling her the best of her generation.",
    question: "As used in the passage, 'acclaim' most nearly means:",
    choices: ["praise", "income", "criticism", "attention"],
    correct: 0,
    explanation: "Being called the best of a generation is high praise. 'Praise' fits. 'Criticism' is the opposite; 'income' and 'attention' may follow but aren't the meaning.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Even after losing power, the deposed leader retained a measure of clout in the region, and former allies still consulted him before major decisions.",
    question: "As used in the passage, 'clout' most nearly means:",
    choices: ["wealth", "anger", "influence", "secrecy"],
    correct: 2,
    explanation: "Former allies still consulting him shows he can still sway decisions. 'Influence' fits. 'Wealth' isn't mentioned; 'anger' and 'secrecy' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The reviewer's praise was nearly hyperbolic — calling a debut novel 'the greatest book ever written in English' invited eye-rolls even from the author's friends.",
    question: "As used in the passage, 'hyperbolic' most nearly means:",
    choices: ["mathematical", "exaggerated", "humorous", "negative"],
    correct: 1,
    explanation: "Calling a debut the greatest English book ever is wildly overstated. 'Exaggerated' fits. 'Mathematical' is the geometry meaning (hyperbola) and doesn't apply; 'humorous' and 'negative' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The detective's first impression of the suspect was that he was disingenuous: his answers sounded rehearsed and his expressions of grief never quite reached his eyes.",
    question: "As used in the passage, 'disingenuous' most nearly means:",
    choices: ["insincere", "stupid", "guilty", "shy"],
    correct: 0,
    explanation: "Rehearsed answers and unfelt grief suggest pretending. 'Insincere' fits. 'Guilty' may be implied later but isn't the meaning; 'stupid' and 'shy' don't fit the description.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The senator's record on the issue was inscrutable; despite hours of testimony, no one could say with confidence which side she would ultimately support.",
    question: "As used in the passage, 'inscrutable' most nearly means:",
    choices: ["dishonest", "boring", "famous", "mysterious"],
    correct: 3,
    explanation: "No one can read which way she'll vote — her position can't be made out. 'Mysterious' fits. 'Dishonest' adds an accusation; 'boring' and 'famous' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Online petitions can galvanize a community in hours, turning a quiet local issue into a citywide protest by the end of the week.",
    question: "As used in the passage, 'galvanize' most nearly means:",
    choices: ["coat", "energize", "confuse", "divide"],
    correct: 1,
    explanation: "Turning quiet residents into protesters means stirring them to action. 'Energize' fits. 'Coat' is the literal metallurgy meaning (galvanized steel) and doesn't apply; 'confuse' and 'divide' aren't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The opposing arguments were nearly impossible to reconcile: one camp wanted complete privacy, the other complete transparency, and no middle ground seemed acceptable to either side.",
    question: "As used in the passage, 'reconcile' most nearly means:",
    choices: ["balance", "ignore", "publish", "remember"],
    correct: 0,
    explanation: "Finding a middle ground between opposite positions means bringing them into harmony. 'Balance' fits. 'Ignore' would mean abandoning the effort; 'publish' and 'remember' don't match.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "The court's ruling was unequivocal: the search had been illegal, and every piece of evidence collected during it would be thrown out.",
    question: "As used in the passage, 'unequivocal' most nearly means:",
    choices: ["unfair", "complicated", "clear", "temporary"],
    correct: 2,
    explanation: "A ruling that throws out every piece of evidence leaves no doubt. 'Clear' fits. 'Unfair' is a judgment the passage doesn't make; 'complicated' is the opposite; 'temporary' isn't supported.",
  },
  {
    type: "psatRW", subtype: "vocab",
    passage: "Many doctors are wary of prescribing new medications until long-term studies confirm their safety, even when early results look promising.",
    question: "As used in the passage, 'wary' most nearly means:",
    choices: ["bored", "exhausted", "eager", "cautious"],
    correct: 3,
    explanation: "Waiting for long-term studies before prescribing shows careful caution. 'Cautious' fits. 'Eager' is the opposite; 'bored' and 'exhausted' don't match the medical-judgment context.",
  },
]
